#-*-mode: TCL; coding: utf-8;-*-
#/////////////////////////////////////////////////////////////////////////////
# CATEGORIES OF THIS FILE
#  - Calendar Messages
#  - General Tolcon Messages
#  - Tolcon Options Messages
#  - Calendar Options Messages
#  - Object Inspector Messages
#  - Table Messages
#  - Table Options Messages
#  - Edit Table Messages
#  - Set Table Messages
#  - Graph Messages
#  - Graph Options Messages
#  - Selector Colums Graph
#  - Series Graph Messages
#  - Series Graph Options Messages
#  - Autocor Graph Options Messages
#  - Set Graph Messages
#  - Multiple Selector Messages
#  - Editor Messages
#  - Editor Options Messages
#  - Find Messages
#  - Statistics Series Messages
#  - Project Editor Messages
#  - Functions Search
#  - Draw Arima
#/////////////////////////////////////////////////////////////////////////////

#/////////////////////////////////////////////////////////////////////////////
# Calendar Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "January"     "Enero"
mcset es "February"    "Febrero"
mcset es "March"       "Marzo"
mcset es "April"       "Abril"
mcset es "May"         "Mayo"
mcset es "June"        "Junio"
mcset es "July"        "Julio"
mcset es "August"      "Agosto"
mcset es "September"   "Septiembre"
mcset es "October"     "Octubre"
mcset es "November"    "Noviembre"
mcset es "December"    "Diciembre"
mcset es "Sun"  "Do"
mcset es "Mon"  "Lu"
mcset es "Tue"  "Ma"
mcset es "Wed"  "Mi"
mcset es "Thu"  "Ju"
mcset es "Fri"  "Vi"
mcset es "Sat"  "Sa"

#/////////////////////////////////////////////////////////////////////////////
# General Tolcon Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "&File"      "&Archivo"
mcset es "&New"       "&Nuevo"
mcset es "&Open"      "&Abrir"
mcset es "TOL &file"  "&Archivo TOL"
mcset es "&Table"     "&Tabla"
mcset es "&Project"   "&Proyecto"
mcset es "TOL &files" "&Archivos TOL"
mcset es "&Tables"    "&Tablas"
mcset es "&Projects"  "&Proyectos"
mcset es "&Included"  "&Incluidos"
mcset es "Clear"      "Limpiar"
mcset es "&Include"   "&Incluir"
mcset es "Include"    "Incluir"
mcset es "&Recent files"          "A&rchivos recientes"
mcset es "&Recent files (sorted)" "A&rchivos recientes (ordenado)"
mcset es "E&xit"                  "&Salir"
mcset es "Exit the application"   "Salir de la aplicación"
mcset es "Question"               "Pregunta"
mcset es "Are you sure you want to quit?"  "¿Está seguro de que desea salir?"
mcset es "&Tools"           "&Herramientas"
mcset es "Tools"            "Herramientas"
mcset es "TOL Editor"       "Editor de TOL"
mcset es "TOL &Editor"      "&Editor de TOL"
mcset es "&New TOL file"    "&Nuevo archivo TOL"
mcset es "New TOL file"     "Nuevo archivo TOL"
mcset es "&Open TOL file"   "&Abrir archivo TOL"
mcset es "Open TOL file"    "Abrir archivo TOL"
mcset es "TOL &Table Editor"     "Editor de &Tablas de TOL"
mcset es "TOL Table Editor"      "Editor de Tablas de TOL"
mcset es "&New Table"        "&Nueva Tabla"
mcset es "New Table"         "Nueva Tabla"
mcset es "&Open Table"       "&Abrir Tabla"
mcset es "Open Table"        "Abrir Tabla"
mcset es "TOL &Project Editor"     "Editor de &Proyectos de TOL"
mcset es "TOL Project Editor"      "Editor de Proyectos de TOL"
mcset es "&New Project"      "&Nuevo Proyecto"
mcset es "New Project"       "Nuevo Proyecto"
mcset es "&Open Project"     "&Abrir Proyecto"
mcset es "Open Project"      "Abrir Proyecto"
mcset es "Analysis Tools"      "Herramientas de Análisis"
mcset es "Manage Packages"      "Gestiona Paquetes"
mcset es "Draw ACF and PACF of ARIMA Models" \
         "Graficar ACF y PACF de Modelos ARIMA"
mcset es "&Functions Search"           "Búsqueda de &funciones"
mcset es "Functions Search"            "Búsqueda de funciones"
mcset es "&Calendar Expert"  "Experto en &Calendarios"
mcset es "Calendar Expert"   "Experto en Calendarios"
mcset es "C&onnection"       "C&onexión"
mcset es "Connection"       "Conexión"
mcset es "Connection to database" \
                             "Conexión a base de datos"
mcset es "C&onnection to database" \
                             "C&onexión a base de datos"
mcset es "&Bayes SQL"        "&Bayes SQL"
mcset es "Bayes SQL"         "Bayes SQL"
mcset es "&Options"          "&Opciones"
mcset es "Options"           "Opciones"
mcset es "&Window"           "&Ventana"
mcset es "Window"            "Ventana"
mcset es "TOL Inspector"     "Inspector de Objetos TOL"
mcset es "TimeSets"          "Conjuntos temporales"
mcset es "Graphs"            "Gráficos"
mcset es "Files"             "Archivos"
mcset es "Tables"            "Tablas"
mcset es "Projects"          "Proyectos"
mcset es "Close all"         "Cerrar todas"
mcset es "&Help"             "&Ayuda"
mcset es "Help"              "Ayuda"
mcset es "&About"            "&Acerca de"
mcset es "About"             "Acerca de"
mcset es "TOL Objects"       "Objetos de TOL"
mcset es "Grammars"          "Gramáticas"
mcset es "Included Files"    "Archivos Incluidos"
mcset es "Console Objects"   "Objetos de Consola"
mcset es "Objects' Spool"    "Spool de Objetos"
mcset es "Functions"         "Funciones"
mcset es "Variables"         "Variables"
mcset es "Files"             "Archivos"
mcset es "Output"          "Salida"
mcset es "Index"           "Índice"
mcset es "Name"            "Nombre"
mcset es "Content"         "Contenido"
mcset es "Path"            "Camino"
mcset es "Description"     "Descripción"
mcset es "OK"              "Aceptar"
mcset es "Cancel"          "Cancelar"
mcset es "Apply"           "Aplicar"
mcset es "Close"           "Cerrar"
mcset es "Options"         "Opciones"
mcset es "Show Eval Window"    "Mostrar Ventana Eval"
mcset es "Show Output Window"  "Mostrar Ventana Output"
mcset es "Show Info Window"    "Mostrar Ventana Info"
mcset es "Change View Mode"    "Cambiar modo de visualización"
# Eval, Output and Info Windows
mcset es "Compile"         "Compilar"
mcset es "Decompile"       "Decompilar"
mcset es "Show history file"  "Mostrar archivo de histórico"
mcset es "Syntax check"       "Chequear sintaxis"
mcset es "Escape text"        "Escapar texto"
mcset es "Delete all"         "Borrar todo"
mcset es "Delete all the messages of the window of output" \
  "Borrar todos los mensajes de la ventana de salida"

mcset es "Recover from log"   "Recuperar del log"
# Window Menu
mcset es "Tile across"	         "Mosaico"
mcset es "Tile horizontally"   	"Mosaico horizontal"
mcset es "Tile vertically"	     "Mosaico vertical"
mcset es "Cascade"	             "Cascada"
mcset es "Arrange icons"        "Ordenar iconos"
mcset es "Minimize all"	        "Minimizar todo"

#/////////////////////////////////////////////////////////////////////////////
# Tolcon Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "TOLBase Options"           "Opciones de TOLBase"
mcset es "TOL"                       "TOL"
mcset es "Default dates"             "Fechas por defecto"
mcset es "First date"                "Fecha de inicio"
mcset es "Last date"                 "Fecha de fin"
mcset es "Output"                    "Salida"
mcset es "Write"                     "Escritura"
mcset es "Write messages in output window"  \
  "Escribir mensajes en la ventana de output"
mcset es "Errors color"              "Color de errores"
mcset es "Warnings color"            "Color de warnings"
mcset es "Update"                    "Actualización"
mcset es "Update options"            "Opciones de actualización"
mcset es "Update always"             "Actualizar siempre"
mcset es "Update each"               "Actualizar cada"
mcset es "milliseconds"              "milisegundos"
mcset es "Don't update until the end" \
                                     "No actualizar hasta el final"
mcset es "Precision"                 "Precisión"
mcset es "Reduce decimal digits to"  "Reducir el número de decimales a"
mcset es "digits"                    "digitos"
mcset es "Use exponential notation when number has more than" \
  "Usar notación exponencial cuando el número tenga más de"
mcset es "Paths"                      "Rutas"
mcset es "Program paths"              "Rutas a programas"
mcset es "Browser path"               "Ruta al navegador"
mcset es "PDF viewer path"            "Ruta al visor PDF"
mcset es "Help path"                  "Ruta de la ayuda"
mcset es "Executable files"           "Archivos ejecutables"
mcset es "pathexplanation"         \
  "Debe especificar la ruta completa del programa o solamente el nombre del\
 programa en caso de que esté en el path"
mcset es "Search the program path"    "Buscar la ruta del programa"
mcset es "Others"        "Otros"
mcset es "Files included recently"    "Archivos incluidos recientemente"
mcset es "Number of last edited files" \
                                  "Número de archivos editados recientemente"
mcset es "files"                      "archivos"
mcset es "Order by date"              "Orden por fecha"
mcset es "Order alphabetically"       "Orden alfabético"
mcset es "Order reverse alphabetically" \
                                      "Orden alfabético inverso"
mcset es "Language"                   "Lenguaje"
mcset es "Choose language"            "Elegir lenguaje"
mcset es "Language is set when you restart interface"  \
  "El lenguaje será establecido cuando reinicie el interfaz"
mcset es "German"                     "Alemán"
mcset es "English"                    "Inglés"
mcset es "Spanish"                    "Español"
mcset es "French"                     "Francés"
mcset es "Italian"                    "Italiano"
mcset es "Japanese"                   "Japonés"
mcset es "Dutch"                      "Holandés"
mcset es "Portuguese"                 "Portugués"
mcset es "Russian"                    "Ruso"
mcset es "Swedish"                    "Sueco"
mcset es "Chinese"                    "Chino"
mcset es ShowDialogODBC        \
        "Mostrar cuadro de conexión a la Base de Datos al arrancar TOLBase"
mcset es "Make the changes and leave the dialog" \
        "Llevar a cabo los cambios y cerrar el diálogo de opciones"
mcset es "Leave the dialog without apply any change" \
        "Cerrar el diálogo de opciones sin aplicar ningún cambio"
mcset es "Make the changes without leave the dialog" \
        "Llevar a cabo los cambios sin cerrar el diálogo de opciones"
mcset es "TOL Project Editor Options" \
       "Opciones del editor de proyectos de TOL"

mcset es "Object Inspector"           "Inspector de Objetos"
mcset es "Show Object Inspector"      "Visualizar Inspector de Objetos"
mcset es "Object Inspector visualization is set when you restart interface" \
 "El inspector de objetos será o no visualizado al reiniciar el interfaz"
                    
#/////////////////////////////////////////////////////////////////////////////
# Calendar Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Calendar Options"    "Opciones de calendario"
mcset es "General Options"     "Opciones generales"
mcset es "Appareance Options"  "Opciones de Estilo"
mcset es "Highligth Appareance Options" "Opciones de Estilo de Resaltado"
mcset es "Highligth"            "Resaltado"
mcset es "Partial highligth"    "Resaltado parcial"
mcset es "Full highligth"       "Resaltado completo"
mcset es "Type"     "Tipo"
mcset es "Fill"     "Relleno"
mcset es "Outline"  "Contorno"
mcset es "oval"        "ovalado"
mcset es "rectangle"   "cuadrado"
mcset es "Month names"  "Nombres de meses"
mcset es "Weekdays"     "Días de la semana"
mcset es "Month days"   "Días del mes"
mcset es "Day"        "Día"
mcset es "Month"      "Mes"
mcset es "Year"       "Año"
mcset es "Rows"       "Filas"
mcset es "Columns"    "Columnas"
mcset es "Language"   "Lenguaje"
mcset es "TimeSet"    "TimeSet"
mcset es "Sunday starts week" "Semana comienza en domingo"
mcset es "Other days" "Otros días"
mcset es "Zoom In"    "Aumentar Zoom"
mcset es "Zoom Out"   "Disminuir Zoom"
mcset es "Moves to previous year"  "Ir al año anterior"
mcset es "Moves to previous month" "Ir al mes anterior"
mcset es "Moves to next month"     "Ir al mes siguiente"
mcset es "Moves to next year"      "Ir al año siguiente"
mcset es "Moves to previous %1\$d months" "Retroceder %1\$d meses"
mcset es "Moves to next %1\$d months"     "Avanzar %1\$d meses"

#/////////////////////////////////////////////////////////////////////////////
# Object Inspector Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Table matrix"           "Tabular matriz"
mcset es "Draw matrix"            "Graficar matriz"
mcset es "Draw serie"             "Graficar serie"
mcset es "Draw series"            "Graficar series"
mcset es "Table serie"            "Tabular serie"
mcset es "Table series"           "Tabular series"
mcset es "Table statistics"       "Tabular estadísticos"
mcset es "Draw autocorrelation"   "Graficar autocorrelación"
mcset es "Table autocorrelation"  "Tabular autocorrelación"
mcset es "View timeset"           "Ver conjunto temporal"
mcset es "Export matrix"          "Exportar matriz"
mcset es "Draw set"               "Graficar conjunto"
mcset es "Draw set special"       "Graficar conjunto especial"
mcset es "Table set"              "Tabular conjunto"
mcset es "View file"              "Editar archivo"
mcset es "Decompile file"         "Decompilar archivo"
mcset es "View %1\$s's definition"  "Ver definición de %1\$s"
mcset es "Add to spool"            "Añadir al spool"
mcset es "Remove from spool"       "Quitar del spool"
mcset es "To Eval window"          "A la ventana Eval"
mcset es "Select all"              "Seleccionar todo"
mcset es "Toggle selection"        "Invertir selección"
mcset es "Matrix table"            "Tabla de matriz"
mcset es "Time series graph"       "Gráfico de series"
mcset es "Autocorrelation graph"   "Gráfico de autocorrelación"
mcset es "Time series table"       "Tabla de series"
mcset es "Autocorrelation table"   "Tabla de autocorrelación"
mcset es "Statistics table"        "Tabla de estadísticos"
mcset es "TimeSet calendar"        "Calendario de conjunto temporal"
mcset es "TimeSets calendar"       "Calendario de conjuntos temporales"
mcset es "Dispersion graph"        "Gráfico de dispersión de un conjunto"
mcset es "Set table"               "Tabla de conjunto"
mcset es "Object %1\$s is a system TOL object" "El objeto %1\$s es un objeto del sistema TOL"
mcset es "Object %1\$s is not defined in a tol file" "El objeto %1\$s no está definido en un archivo tol"
mcset es "Set not tabulable"       "Conjunto no tabulable"
mcset es "Set not graficable"      "Conjunto no graficable"
mcset es "Function %1\$s couldn't be stored in spool" \
  "La función %1\$s no pudo guardarse en el spool"
mcset es VarWithoutNameNotFunc \
  "No se pueden aplicar ninguna función sobre un objeto global sin nombre"
mcset es "Series graph" "Gráfico de series"

#/////////////////////////////////////////////////////////////////////////////
# Functions search Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Search functions"            "Buscar funciones"
mcset es "of grammars"                 "de las gramáticas"
mcset es "whose name contains"         "cuyo nombre contiene"
mcset es "whose description contains"  "cuya descripción contiene"
mcset es "and with at least"           "y con al menos"
mcset es "parameters"                  "parámetros"
mcset es "in which one is of type"     "en el que uno es de tipo"
mcset es "and whose name contains"     "y cuyo nombre contiene"
mcset es "Has not been any coincident result" "No se han encontrado resultados coincidentes"
mcset es "Message"                     "Mensaje"

#/////////////////////////////////////////////////////////////////////////////
# Table Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Export"    "Exportar"
mcset es "Free Headers"    "Cabeceras libres"
mcset es "Fixed Headers"   "Cabeceras fijas"
mcset es "Save"      "Guardar"
mcset es "Save as"   "Guardar como"
mcset es "Save As"   "Guardar como"
mcset es "Warning"   "Aviso"
mcset es "File hasn't been saved" "No se ha guardado el fichero"
mcset es "Back"      "Anterior"
mcset es "Next"      "Siguiente"
mcset es "Filter"    "Filtrar"
mcset es "Row"       "Fil"
mcset es "Col"       "Col"
mcset es "rows"      "filas"
mcset es "title"     "título"
mcset es "Eliminate" "Eliminar"
mcset es "Not connected"    "No conectado"
mcset es "Connect Options"  "Opciones de conexión"
mcset es "Open query"       "Abrir query"
mcset es "Save query"       "Guardar query"
mcset es "Execute query"    "Ejecutar query"
mcset es "Object inspector" "Inspector de objetos"
mcset es "You must set connection first" \
        "Antes debe establecer una conexión"

#/////////////////////////////////////////////////////////////////////////////
# Table Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Table Options"      "Opciones de Tabla"
mcset es "Export"    "Exportar"
mcset es "Style"     "Estilo"
mcset es "Columns separator"  "Separador de columnas"
mcset es "Rows separator"     "Separador de filas"
mcset es "Tab"     "Tabulador"
mcset es "Return"  "Salto de línea"
mcset es "Other"   "Otro"
mcset es "Number of rows to use as title area"     "Número de filas de título"
mcset es "Number of columns to use as title area"  "Número de columnas de título"
mcset es "Allow title cells in the selection"      "Permitir seleccionar celdas de título"

#/////////////////////////////////////////////////////////////////////////////
# Edit Table Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "New white table"   "Nueva tabla en blanco"
mcset es "Table %1\$s has changed!" "¡La tabla del archivo %1\$s ha cambiado!"

#/////////////////////////////////////////////////////////////////////////////
# Set Table Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Set not tabulable"   "Conjunto no tabulable"

#/////////////////////////////////////////////////////////////////////////////
# Graph Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Zoom extend"                 "Volver al zoom original"
mcset es "Zoom frame"                  "Expandir región"
mcset es "Scroll view"                 "Mover el marco de la imagen"
mcset es "Toggle grid mode"            "Cambiar modo de grid"
mcset es "Toggle crosshair mode"       "Cambiar modo de puntero"
mcset es "Skip to first data"          "Saltar al primer dato"
mcset es "Play backward"               "Reproducir hacia atrás"
mcset es "Stop playing"                "Parar reproducción"
mcset es "Play forward"                "Reproducir hacia delante"
mcset es "Skip to last data"           "Saltar al último dato"
mcset es "Take a photo of the graphic" "Guardar una foto del gráfico"
mcset es "Copy to clipboard"           "Copiar al portapapeles"
mcset es "View as table"               "Ver como tabla"
mcset es "Changes type for all elements in graph" \
   "Cambia el tipo a todos los elementos del gráfico"
mcset es "Graphic Options"             "Opciones del gráfico"
mcset es "Load graph options from a Graphic Configuration File" \
 "Cargar opciones de gráfico desde un GCF (archivo de configuración de gráficos)"
mcset es "Save the current graph options in a Graphic Configuration File" \
 "Salvar opciones de gráfico a un GCF (archivo de configuración de gráficos)"
mcset es "Number format"               "Formato de números"

#/////////////////////////////////////////////////////////////////////////////
# Graph Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Graph Options"   "Opciones de gráfico"
mcset es "General"         "General"
mcset es "Axis"            "Ejes"
mcset es "Titles"          "Títulos"
mcset es "Lines"           "Líneas"
mcset es "Data"            "Datos"
mcset es "Marker"          "Marcador"
mcset es "Markers"         "Marcadores"
mcset es "Grid"            "Rejilla"
mcset es "Legend"          "Leyenda"
mcset es "Style"           "Estilo"
mcset es "Fill"            "Relleno"
mcset es "X Axis"          "Eje X"
mcset es "Y Axis"          "Eje Y"
mcset es "Ticks"           "Marcas"
mcset es "First"           "Primero"
mcset es "Last"            "Ultimo"
mcset es "Min"             "Mínimo"
mcset es "Max"             "Máximo"
mcset es "All values"      "Todos los valores"
mcset es "Total"           "Total"
mcset es "Each"            "Cada"
mcset es "Automatic"       "Automático"
mcset es "X2 Axis"         "Eje X2"
mcset es "Y2 Axis"         "Eje Y2"
mcset es "Show X2 axis"    "Mostrar eje X2"
mcset es "Show Y2 axis"    "Mostrar eje Y2"
mcset es "Data values"     "Valores en datos"
mcset es "Data symbols"    "Símbolos en datos"
mcset es "Show"         "Mostrar"
mcset es "both"         "ambos"
mcset es "none"         "ninguno"
mcset es "Show ticks"   "Mostrar marcas"
mcset es "Font"         "Fuente"
mcset es "Color"        "Color"
mcset es "Shadow"       "Sombra"
mcset es "Rotate"       "Rotar"
mcset es "Length"       "Longitud"
mcset es "Subdivisions" "Subdivisiones"
mcset es "Graph Title"  "Título del Gráfico"
mcset es "Axis Titles"  "Títulos de los Ejes"
mcset es "X axis"       "eje X"
mcset es "Y axis"       "eje Y"
mcset es "X2 axis"      "eje X2"
mcset es "Y2 axis"      "eje Y2"

mcset es "Lines"        "Líneas"
mcset es "and"          "y"
mcset es "Bars"         "Barras"
mcset es "Bars Width"   "Ancho de barras"
mcset es "Lines Width"  "Ancho de líneas"
mcset es "Lines Type"   "Tipo de líneas"
mcset es "Smooth"       "Suavizado"
mcset es "linear"       "lineal"
mcset es "step"         "escalón"
mcset es "natural"      "natural"
mcset es "quadratic"    "cuadrático"
mcset es "Bar mode"     "Tipo de barras"
mcset es "aligned"      "alineadas"
mcset es "stacked"      "apiladas"
mcset es "overlap"      "solapadas"
mcset es "infront"      "superpuestas"
mcset es "Bar relief"   "Relieve de barras"
mcset es "Elements order"  "Orden de los elementos"
mcset es "Favourite line colors"  "Colores de líneas predeterminados"
mcset es "Color"       "Color"
mcset es "Width"     "Grosor"
mcset es "Decimals"  "Decimales"
mcset es "Anchor"    "Alineación"    
mcset es "Show symbols"  "Mostrar símbolos"
mcset es "Symbol"    "Símbolo"
mcset es "circle"    "círculo"
mcset es "square"    "cuadrado"
mcset es "diamond"   "diamante"
mcset es "plus"      "más"
mcset es "cross"     "cruz"
mcset es "splus"     "peq más"
mcset es "scross"    "peq cruz"
mcset es "triangle"  "triángulo"
mcset es "arrow"     "flecha"
mcset es "Pixels"    "Pixels"
mcset es "Scale symbols"  "Escalar símbolos"
mcset es "Outline width"  "Ancho contorno"
mcset es "Grid options"      "Opciones de rejilla"
mcset es "Line width"        "Ancho de línea"
mcset es "Draw for minor ticks"    "Dibujar con marcas menores"
mcset es "Map X to"          "Mapear X a"
mcset es "Map Y to"          "Mapear Y a"
mcset es "Legend options"    "Opciones de leyenda"
mcset es "Hide legend"       "Ocultar leyenda"
mcset es "Background"        "Color de fondo"
mcset es "Border width"      "Ancho borde"
mcset es "Relief"            "Relieve"
mcset es "flat"        "plano"
mcset es "groove"      "ranurado"
mcset es "raised"      "levantado"
mcset es "ridge"       "encrestado"
mcset es "solid"       "sólido"
mcset es "sunken"      "hundido"
mcset es "Position"          "Posición"
mcset es "left"      "izquieda"
mcset es "right"     "derecha"
mcset es "top"       "arriba"
mcset es "bottom"    "abajo"
mcset es "plotarea"  "gráfico" 
mcset es "Raised"            "Levantado"
mcset es "X pad (left | right)"   "Espacio en X (izquierda | derecha)"
mcset es "Y pad (top | bottom)"   "Espacio en Y (arriba | abajo)"
mcset es "Internal"     "Interno"
mcset es "External"     "Externo"
mcset es "Graph"     "Gráfico"
mcset es "Exterior Area"   "Area exterior"
mcset es "MARGINS"  "MARGENES"
mcset es "Left"    "Izquieda"
mcset es "Right"   "Derecha"
mcset es "Top"     "Arriba"
mcset es "Bottom"  "Abajo"
mcset es "auto"    "auto"
mcset es "Plot Area"       "Area de Dibujo"
mcset es "PAD"     "ESPACIOS"
mcset es "Invert X-Y axis"   "Intercambiar ejes X-Y"
mcset es "Change color"      "Cambiar color"
mcset es "Without color"     "Sin color"
mcset es "Change font"       "Cambiar fuente"
mcset es "Change Shadow"     "Cambiar color de sombra"
mcset es "Title"     "Título"
mcset es "Line"      "Línea"
mcset es "Common Options"     "Opciones comunes"
mcset es "Line Options"       "Opciones de línea"
mcset es "Bar Options"        "Opciones de barra"
mcset es "Hide element"       "Ocultar elemento"
mcset es "Change type"        "Cambiar tipo"
mcset es "Marker already inserted" "Marcador ya insertado"
mcset es "Fill options"  "Opciones de relleno"
mcset es "Choose fill type, image or foreground and backgrounds colors for 5 Lines"\
  "Eliga tipo de relleno, imagen o color y color de fondo para las 5 primeras líneas"
mcset es "Fill type"  "Tipo de relleno"
mcset es "Image"      "Imagen"
mcset es "image"      "imagen"
mcset es "striped"    "rayado"
mcset es {stipple image}    {Fondo con imagen}
mcset es {stipple degraded} {Fondo degradado}
mcset es {Image background} {Imagen de fondo}
mcset es {Degraded percentage} {Porcentaje degradado}
mcset es "Fill next lines after 5 with default style" \
  "Rellenar las siguientes líneas a partir de la 5ª con el estilo por defecto"
mcset es "ForNumOpc:-" "Espeficica que la conversión se justifica a la izquierda"
mcset es "ForNumOpc:+" "Especifica que el número se muestra con signo" 
mcset es "ForNumOpc:Space" \
  "Especifica que se añade un espacio al principio del numero si el primer carácter no es el signo"
mcset es "ForNumOpc:Zero" \
  "Especifica que el número de debe de rellenar a la izquiera con ceros en lugar de espacios"
mcset es "ForNumOpc:f" \
  "Convierte un número decimal con signo en coma flotante en un carácter con la forma xx.yy,\n\
   donde el número 'y' determina la precisión (por defecto 6).\n\
   Si la precisión es cero, no existirá el punto decimal en la salida"
mcset es "ForNumOpc:e" \
  "Convierte un número decimal con signo a notación cientifica con la forma x.yyye±zz,\n\
   donde el número 'y' determina la precisión (por defecto 6).\n\
   Si la precisión es cero, no existirá el punto decimal en la salida.\n\
   Si E es usado, se mostrara en la salida E en lugar de e"
mcset es "ForNumOpc:g" \
  "Si el exponente es menor que -4 o mayor o igual que la precisión,\n\
   la conversión del número en coma flotante se realiza con %e o %E.\n\
   En otro caso usara %f. Se omiten los ceros y el punto decimal que se arrastran"
mcset es "No conversion: just insert %" "No realiza conversión, inserta %"
mcset es "It proves the specified format" "Prueba el formato especificado"
mcset es "Prove" "Prueba"
mcset es "AddMarkSel"              "Añade la marca a la selección"
mcset es "Scales"                  "Escalas"
mcset es "Date"                    "Fecha"
mcset es "Number"                  "Número"
mcset es "Text"                    "Texto"
mcset es "By defect"               "Por defecto"
mcset es "Specified"               "Especificadas"
mcset es "Main title"              "Título del gráfico"
mcset es "Self fit of values"      "Auto-ajuste a valores"
mcset es "Self fit of axes to the data of the graph to open" \
         "Autoajustar los ejes del gráfico a los valores al abrir"
mcset es {For all element options} {Para todos los elementos}
mcset es {Lines list}              {Lista de líneas}
mcset es {Hide line}               {Ocultar línea}
mcset es {Foreground}              {Primer plano}
mcset es "Show percent"            "Mostrar porcentaje"
mcset es "Format number"           "Formato de números"
mcset es "In"                      "En"
mcset es "Markers Style"           "Estilo de los marcadores"
mcset es "Choose lines color, type, position and width for 5 Markers" \
           "Escoja el color de las líneas, su tipo posición y anchura para los 5 marcadores"
mcset es "Mapped"          "Mapeo"
mcset es "Bar"             "Barra"
mcset es "Choose file"             "Barra"


#/////////////////////////////////////////////////////////////////////////////
# Selector Colums Graph
#/////////////////////////////////////////////////////////////////////////////
mcset es "Select series"          "Seleccionar series"
mcset es "Automatic generation"   "Generación automática"
mcset es SetGraphAllFirst         "Todas contra la primera"
mcset es SetGraphAllFirstHint     "Genera todas las combinaciones posibles\
 para graficar la primera columna con las demas"
mcset es SetGraphAllGeneric       "Todas contra la genérica"
mcset es SetGraphAllGenericHint   "Genera todas las combinaciones posibles\
 para graficar la columna genérica con las demas"
mcset es SetGraphEvenUneven       "Impares contra pares"
mcset es SetGraphEvenUnevenHint   "Genera las combinaciones posibles de\
 impares contra pares.\n  1 contra 2, 3 contra 4, etc."

#/////////////////////////////////////////////////////////////////////////////
# Series Graph Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Show/Hide Average"       "Mostrar/Ocultar Media"     
mcset es "Show/Hide Std. Dev."     "Mostrar/Ocultar Dev. Std."
mcset es "View Statistics table"   "Ver tabla de estadísticos"

#/////////////////////////////////////////////////////////////////////////////
# Series Graph Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Date Format"   "Formato fechas"
mcset es "Axis"          "Ejes"
mcset es "X-Markers"     "Marcadores en X"
mcset es "Y-Markers"     "Marcadores en Y"
mcset es "TOL Long Format"  "Formato largo de TOL"
mcset es "TOL Short Format" "Formato corto de TOL"
mcset es "User Defined"     "Definido por el usuario"
mcset es "Format String" "Cadena de formato"
mcset es "Format"   "Formato"
mcset es "String"   "Cadena"
mcset es "Sample"   "Ejemplo"
mcset es "Format Specifiers"  "Especificadores de formato"
mcset es "Long Weekday"             "Día de la semana (largo)"
mcset es "Long Month Name"          "Nombre del mes (largo)"
mcset es "Short Weekday"            "Día de la semana (corto)"
mcset es "Short Month Name"         "Nombre del mes (corto)"
mcset es "Day Number"               "Día del mes"
mcset es "Month Number"             "Número de mes"
mcset es "Two Year Digit"           "Año (2 dígitos)"
mcset es "Four Year Digit"          "Año (4 dígitos)"
mcset es "Forze uncompleted dates"  "Fechas incompletas"
mcset es "Forze completed dates"    "Fechas completas"
mcset es "Percent symbol (%)"       "Símbolo de porcentaje (%)"
mcset es "X-Axis Ticks"               "Marcas para el eje X"
mcset es "Select TimeSets for axis" \
  "Seleccione los conjuntos temporales para los ejes"
mcset es "Select TimeSets to mark"  \
  "Seleccione los conjuntos temporales a marcar"
mcset es "X-Markers Style"     "Estilo de los marcadores en X"
mcset es "Choose lines color, type and width for 5 X-Markers"\
  "Elija el color, estilo y grosor de las líneas para los 5 \
 primeros marcadores en X"
mcset es "Select Statistics to mark"  "Seleccione los estadísticos a marcar"
mcset es "of"  "de"
mcset es "Cant draw '%1\$s' y marker because its value is ?" \
 "No se puede dibujar el marcador en Y '%1\$s' porque su valor es ?"
mcset es "showDesc"    "Mostrar la descripción como nombre de la serie"
mcset es "Rest"        "Resto"
mcset es "Draw Average +- " "Dibujar media +- "
mcset es "Under"           "Por encima"

#/////////////////////////////////////////////////////////////////////////////
# Autocor Graph Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Autocorrelation"       "Autocorrelación"
mcset es "Parameters"            "Parámetros"
mcset es "Numbers of lags"       "Número de lags"
mcset es "Sigma factor"          "Factor de sigma"
mcset es "Sigma value"           "Valor de sigma"

#/////////////////////////////////////////////////////////////////////////////
# Set Graph Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Set not graphicable"  "Conjunto no graficable"
mcset es "Columns Selector"     "Selector de columnas"
mcset es "X Values"             "Valores en X"
mcset es "Y Values"             "Valores en Y"
mcset es "Series to draw"       "Series a dibujar"
mcset es "Add"                  "Añadir"
mcset es "Delete"               "Borrar"
mcset es "You must fill X Values"    "Debe rellenar Valores en X"
mcset es "You must fill Y Values"    "Debe rellenar Valores en Y"
mcset es "You must specify a name"   "Debe especificar un nombre"
mcset es "Item not selectionable"    "Elemento no seleccionable"
mcset es "UniqueXAxis"     "Si elige una columna de texto, fechas o genérica \
 para los valores en X de una serie, debe elegir esa columna como valores en \
 X de todas las series."
mcset es "You have added another serie with this name" \
 "Ya ha añadido una serie con ese nombre"
mcset es "You must select a serie"   "Debe seleccionar una serie"
mcset es "Series do not exist that to draw" "No existen series que dibujar"
mcset es "No selection information related" \
 "No hay información asociada a la selección"

#/////////////////////////////////////////////////////////////////////////////
# Multiple Selector Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Multiple Selector"  "Selector Múltiple"
mcset es "Not selected"       "No seleccionados"
mcset es "Selected"           "Seleccionados"
mcset es "Moves selection from left to right" \
  "Pasa la selección de la izquierda a la derecha"
mcset es "Moves selection from right to left" \
  "Pasa la selección de la derecha a la izquierda"
mcset es "Moves all from left to right"  \
  "Pasa todos de la izquierda a la derecha"
mcset es "Moves all from rigth to left"  \
  "Pasa todos de la derecha a la izquierda"
mcset es "Accept selection"  "Aceptar la selección"
mcset es "Cancel selection"  "Cancelar la selección"

#/////////////////////////////////////////////////////////////////////////////
# Editor Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Bayes Editor"   "Editor de Bayes"
mcset es "Saved"        "Guardado"
mcset es "Not Saved"    "No guardado"
mcset es "New white document"               "Nuevo documento en blanco"
mcset es "Open"        "Abrir"
mcset es "Save"        "Guardar"
mcset es "Save as"     "Guardar como"
mcset es "Print"       "Imprimir"
mcset es "Preview"     "Presentación preliminar"
mcset es "Find"         "Buscar"
mcset es "Find next"    "Buscar siguiente"
mcset es "Replace"      "Remplazar"
mcset es "Replace all"  "Remplazar todo"
mcset es "Replace with" "Remplazar con"
mcset es "Edit"        "Edición"
mcset es "Cut"         "Cortar"
mcset es "Copy"        "Copiar"
mcset es "Paste"       "Pegar"
mcset es "Select all"  "Seleccionar todo"
mcset es "Delete"      "Borrar"
mcset es "Undo"        "Deshacer"
mcset es "Redo"        "Rehacer"
mcset es "Indent"       "Aumentar sangría"
mcset es "Unindent"     "Disminuir sangría"
mcset es "Font"        "Fuente"
mcset es "Save and Compile"  "Guardar y compilar"
mcset es "Decompile"         "Decompilar"
mcset es "Refresh"           "Refrescar"
mcset es "Help on line"      "Ayuda"
mcset es "Show line numbers"         "Mostrar número de líneas"
mcset es "Enable mark line numbers"  "Permitir marcar número de líneas"
mcset es "Show right margin line"   \
  "Mostrar/Ocultar línea de margen derecho"
mcset es "Not Compiled"      "No compilado"
mcset es "Compiled"          "Compilado"
mcset es "Compiling"         "Compilando"
mcset es "Insert"            "Insertar"
mcset es "Overwrite"         "Sobrescribir"
mcset es "lines"             "líneas"
mcset es "Header file %1\$s doesn't exist"  \
  "El archivo de cabecera %1\$s no existe"
mcset es "Functions file header %1\$s doesn't exist"  \
  "El archivo de cabecera de funciones %1\$s no existe"
mcset es "Check editor's options"     "Verifique las opciones del editor"
mcset es "Insert function schema"     "Insertar plantilla de función"
mcset es "File %1\$s has changed!"    \
  "¡El texto del archivo %1\$s ha cambiado!"
mcset es "Do you want to save changes?"     \
  "¿Desea guardar los cambios?"
mcset es "Syntax errors in file"            \
  "Archivo con errores sintácticos"
mcset es "Look over output window"          \
  "Revise la ventana de output"
mcset es "Syntax check done successfully"   \
  "Revisión sintáctica realizada satisfactoriamente"
mcset es "Syntax check cannot be done"      \
  "No se ha podido realizar la revisión sintáctica"
mcset es "File already opened!"            \
  "¡El fichero ya está abierto!"
mcset es "has been changed externally!"     \
  "ha sido modificado externamente."
mcset es "Do you want to rewrite it and save new changes?" \
  "¿Desea reescribirlo de todos modos y guardar sus nuevos cambios?"
mcset es "Editor Options"  "Opciones del editor"
mcset es "Search function" "Buscar función"
mcset es "CVS Utilities" "Utilidades CVS"

#/////////////////////////////////////////////////////////////////////////////
# Editor Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Headers"                    "Cabeceras"
mcset es "Others"                     "Otros"
mcset es "Files of headers"           "Archivos de cabeceras"
mcset es "Insert header in new files" "Insertar cabecera en archivos nuevos"
mcset es "Files Header"               "Cabecera de archivos"
mcset es "Functions Header"           "Cabecera de funciones"
mcset es "Files edited recently"      "Archivos editados recientemente"
mcset es "files"                      "archivos"
mcset es "Show line at"               "Mostrar línea en"
mcset es "characters"                 "caracteres"
mcset es "Characters to indent"       "Caracteres a indentar"
mcset es "CVS Options"                "Opciones de CVS"
mcset es "Show differences"           "Mostrar diferencias"
mcset es "Open TkCVS"                 "Abrir TkCVS"

#/////////////////////////////////////////////////////////////////////////////
# Find Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Case sensitive"    "Coincidir mayúsculas y minúsculas"
mcset es "Direction"         "Dirección"
mcset es "Forward"           "Abajo"
mcset es "Backward"          "Arriba"
mcset es "SearchUpEndDoc"    "Ha alcanzado el final del documento"
mcset es "SearchUpBeginDoc"  "Ha alcanzado el principio del documento"
mcset es "FindFromBegin"     "¿Desea continuar desde el principio del documento?" 
mcset es "FindFromEnd"       "¿Desea continuar desde el final del documento?"

#/////////////////////////////////////////////////////////////////////////////
# Statistics Series Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "Count"       "Longitud"
mcset es "Maximun"     "Máximo"
mcset es "Minimun"     "Mínimo"
mcset es "Sum"         "Suma"
mcset es "Average"     "Media"
mcset es "Std. Dev."   "Desv. Est."
mcset es "Varianze"    "Varianza"
mcset es "Asimetry"    "Asimetría"
mcset es "Kurtosis"    "Kurtosis"
mcset es "Median"      "Mediana"

#/////////////////////////////////////////////////////////////////////////////
# Project Editor Messages
#/////////////////////////////////////////////////////////////////////////////
mcset es "New white project"   "Nuevo proyecto en blanco"
mcset es "Project"             "Proyecto"
mcset es "Add node"            "Añadir nodo"
mcset es "Open node"           "Abrir nodo"
mcset es "Delete node"         "Borrar nodo"
mcset es "Attributes"          "Atributos"
mcset es "Compile node"        "Compilar nodo"
mcset es "Decompile node"      "Decompilar nodo"
mcset es "Compile to the end"  "Compilar hasta el final"
mcset es "Compile up to here"  "Compilar hasta aquí"
mcset es "Select node type"    "Seleccionar tipo de nodo"
mcset es "Node type"           "Tipo de nodo"
mcset es "TOL file"            "Archivo TOL"
mcset es "BDT file"            "Archivo BDT"
mcset es "BST file"            "Archivo BST"
mcset es "Folder"              "Carpeta"
mcset es "folder"              "carpeta"
mcset es "a file of type"      "archivo"
mcset es "Continue"            "Continuar"
mcset es "File name"           "Nombre de archivo"
mcset es "Exclude in TOLBase"  "Excluir en TOLBase"
mcset es "Exclude in tol.exe"  "Excluir en tol.exe"
mcset es "Are you sure you want to delete node %1\$s?" \
       "¿Está seguro de que desea borrar el nodo %1\$s?"

#/////////////////////////////////////////////////////////////////////////////
#  - Functions Search
#/////////////////////////////////////////////////////////////////////////////
mcset es "There isn't grammars where search"   \
         "Se debe introducir alguna gramática donde realizar la búsqueda"
mcset es "There aren't sufficient criteria search"   \
      "No se han introducido suficientes criterios para realizar la búsqueda"
mcset es "Criteria search for the name are incorrect"   \
         "Los criterios de búsqueda para el nombre son incorrectos"
mcset es "Criteria search for the description are incorrect"   \
         "Los criterios de búsqueda para la descripción son incorrectos"
mcset es "View definition"           "Ver definición"         

#/////////////////////////////////////////////////////////////////////////////
#  - Draw Arima
#/////////////////////////////////////////////////////////////////////////////
mcset es "Date first"          "Fecha inicial"
mcset es "Date last"           "Fecha final"
mcset es "Draw"                "Graficar"
mcset es "All the required parameters must be filled" \
                "Se deben rellenar todos los parámetros requeridos"
mcset es "The date last must be higher than the date first" \
                "La fecha final debe ser posterior que la fecha inicial"
mcset es "Dates do not have the correct format" \
                "Las fechas no tienen formato correcto"
mcset es "Date Selector"       "Selector de fechas"
mcset es "Graph of ACFs and PACFs of ARIMA Model" \
                "Gráfico de ACFs y PACFs del Modelo ARIMA"
mcset es "Parameters of the graph" \
                "Parámetros del gráfico"
mcset es "Date first required" "Fecha de inicio requerida"
mcset es "Date last required"  "Fecha final requerida"
mcset es "Draw ACF and PACF of ARIMA Model" \
                "Graficar ACF y PACF del modelo ARIMA"
                
#/////////////////////////////////////////////////////////////////////////////
# General for ProgressBar
#/////////////////////////////////////////////////////////////////////////////
mcset es {Creation of the form}          {Creación del formulario}
mcset es {Recovering values of the configuration file} \
           {Recuperando valores del archivo de configuración}

#/////////////////////////////////////////////////////////////////////////////
# Create Button Dialog
#/////////////////////////////////////////////////////////////////////////////
mcset es "Create button" "Crear el botón"
mcset es "Create" "Crear"
mcset es "Form" "Formulario"
mcset es "Tooltip" "Ayuda"
mcset es "New Button Wizard" "Creación de Nuevo Botón"
mcset es "Image Selection" "Selección de imagen"

#///////////////////////////////////////////////////////////////////////////
# Manage Package
#/////////////////////////////////////////////////////////////////////////////
mcset es "Add New Repository" "Añadir Repositorio Nuevo"
mcset es "Check Repository" "Chequear Repositorio"
mcset es "Selected" "Seleccionados"
mcset es "All" "Todos"
mcset es "Sync with servers" "Sincroniza con servidores"
mcset es "Install %s" "Instala %s"
mcset es "Install selected" "Instala seleccionados"
mcset es "Install ZIP" "Instala ZIP"
mcset es "Update %s" "Actualiza %s"
mcset es "Update selected" "Actualiza seleccionados"
mcset es "Update all" "Actualiza todos"
mcset es "Upgrade %s" "Mejora %s"
mcset es "Upgrade selected" "Mejora los seleccionados"
mcset es "Upgrade all" "Mejora todos"
mcset es "Export %s" "Exporta %s"
mcset es "Export selected" "Exporta los seleccionados"
mcset es "Export all" "Exporta todos"
mcset es "Import SyncInfo" "Importa SyncInfo"
mcset es "Export SyncInfo" "Exporta SyncInfo"
mcset es "Status" "Estado"
mcset es "Repository" "Repositorio"
mcset es "new (%s)" "nuevo (%s)"
mcset es "new" "nuevo"
mcset es "upgrade (%s)" "mejora (%s)"
mcset es "unknown" "desconocido"
mcset es "update" "actualizar"
mcset es "update/%s" "actualizar/%s"
mcset es "Remove all for %s" "Borrar todo para %s"
mcset es "Remove %s" "Borrar %s"
mcset es "Remove selected" "Borrar los seleccionados"
mcset es "Remove all" "Borrar todo"
