/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hcarralero_toljava_TOLMachine */

#ifndef _TOLJAVAJNI_H
#define _TOLJAVAJNI_H
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeInitTOL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeInitTOL
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeExecute
 * Signature: (Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeExecute
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeCallCode
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeCallCode
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetVariable
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetVariable
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeSetVariableValue
 * Signature: (Ljava/lang/String;Lcom/hcarralero/toljava/TOLLObject;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeSetVariableValue
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetTextVariables
 * Signature: ()[Lcom/hcarralero/toljava/TOLVariable;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetTextVariables
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetRealVariables
 * Signature: ()[Lcom/hcarralero/toljava/TOLVariable;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetRealVariables
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetDateVariables
 * Signature: ()[Lcom/hcarralero/toljava/TOLVariable;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetDateVariables
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetComplexVariables
 * Signature: ()[Lcom/hcarralero/toljava/TOLVariable;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetComplexVariables
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetMatrixVariables
 * Signature: ()[Lcom/hcarralero/toljava/TOLVariable;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetMatrixVariables
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetVMatrixVariables
 * Signature: ()[Lcom/hcarralero/toljava/TOLVariable;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetVMatrixVariables
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetPolynVariables
 * Signature: ()[Lcom/hcarralero/toljava/TOLVariable;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetPolynVariables
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetRatioVariables
 * Signature: ()[Lcom/hcarralero/toljava/TOLVariable;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetRatioVariables
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetCodeVariables
 * Signature: ()[Lcom/hcarralero/toljava/TOLVariable;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetCodeVariables
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetSerieVariables
 * Signature: ()[Lcom/hcarralero/toljava/TOLVariable;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetSerieVariables
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetTimeSetVariables
 * Signature: ()[Lcom/hcarralero/toljava/TOLVariable;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetTimeSetVariables
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetSetVariables
 * Signature: ()[Lcom/hcarralero/toljava/TOLVariable;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetSetVariables
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeGetNameBlocks
 * Signature: ()[Lcom/hcarralero/toljava/TOLNameBlock;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeGetNameBlocks
  (JNIEnv *, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeSerieGetValue
 * Signature: (Ljava/lang/String;Lcom/hcarralero/toljava/TOLDate;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeSerieGetValue__Ljava_lang_String_2Lcom_hcarralero_toljava_TOLDate_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeSerieGetValue
 * Signature: (Ljava/lang/String;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeSerieGetValue__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeSerieGetItems
 * Signature: (Ljava/lang/String;Lcom/hcarralero/toljava/TOLDate;I)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeSerieGetItems__Ljava_lang_String_2Lcom_hcarralero_toljava_TOLDate_2I
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeSerieGetItems
 * Signature: (Ljava/lang/String;II)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeSerieGetItems__Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeSerieGetFirstDate
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeSerieGetFirstDate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeSerieGetLastDate
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeSerieGetLastDate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeTimeSetGetDates
 * Signature: (Ljava/lang/String;Lcom/hcarralero/toljava/TOLDate;I)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeTimeSetGetDates
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeTimeSetGetPrevDate
 * Signature: (Ljava/lang/String;Lcom/hcarralero/toljava/TOLDate;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeTimeSetGetPrevDate
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeTimeSetGetNextDate
 * Signature: (Ljava/lang/String;Lcom/hcarralero/toljava/TOLDate;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeTimeSetGetNextDate
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeSetGetSize
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeSetGetSize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeSetGetElement
 * Signature: (Ljava/lang/String;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeSetGetElement
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_hcarralero_toljava_TOLMachine
 * Method:    nativeSetGetElements
 * Signature: (Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hcarralero_toljava_TOLMachine_nativeSetGetElements
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
