GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX,
    ALTER, CREATE TEMPORARY TABLES, LOCK TABLES
    ON toltests.* TO 'toltester'@'192.168.1.%' IDENTIFIED BY 'pwdtt';
    
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX,
    ALTER, CREATE TEMPORARY TABLES, LOCK TABLES
    ON toltests.* TO 'toltester' IDENTIFIED BY 'pwdtt';
    
FLUSH PRIVILEGES;
