/*
 The contents of this file was generated using gen_blapi_h.tcl for the
 source file mkl_blas.h
*/
float FORTRAN (*ptr_sasum)(int *n,float *x,int *incx);
void FORTRAN (*ptr_saxpy)(int *n,float *alpha,float *x,int *incx,float *y,int *incy);
float FORTRAN (*ptr_scasum)(int *n,blapi_complex8_t *x,int *incx); 
float FORTRAN (*ptr_scnrm2)(int *n,blapi_complex8_t *x,int *incx); 
void FORTRAN (*ptr_scopy)(int *n,float *x,int *incx,float *y,int *incy);
float FORTRAN (*ptr_sdot)(int *n,float *x,int *incx,float *y,int *incy);
float FORTRAN (*ptr_snrm2)(int *n,float *x,int *incx);
void FORTRAN (*ptr_srot)(int *n,float *x,int *incx,float *y,int *incy,float *c,float *s);
void FORTRAN (*ptr_srotg)(float *a,float *b,float *c,float *s);
void FORTRAN (*ptr_sscal)(int *n,float *a,float *x,int *incx);
void FORTRAN (*ptr_sswap)(int *n,float *x,int *incx,float *y,int *incy);
int FORTRAN (*ptr_isamax)(int *n,float *x,int *incx);
void FORTRAN (*ptr_caxpy)(int *n,blapi_complex8_t *alpha,blapi_complex8_t *x,int *incx,blapi_complex8_t *y,int *incy); 
void FORTRAN (*ptr_ccopy)(int *n,blapi_complex8_t *x,int *incx,blapi_complex8_t *y,int *incy); 
void FORTRAN (*ptr_cdotc)(blapi_complex8_t *pres,int *n,blapi_complex8_t *x,int *incx,blapi_complex8_t *y,int *incy); 
void FORTRAN (*ptr_cdotu)(blapi_complex8_t *pres,int *n,blapi_complex8_t *x,int *incx,blapi_complex8_t *y,int *incy); 
void FORTRAN (*ptr_crotg)(blapi_complex8_t *a,blapi_complex8_t *b,float *c,blapi_complex8_t *s); 
void FORTRAN (*ptr_cscal)(int *n,blapi_complex8_t *a,blapi_complex8_t *x,int *incx); 
void FORTRAN (*ptr_csscal)(int *n,float *a,blapi_complex8_t *x,int *incx); 
void FORTRAN (*ptr_cswap)(int *n,blapi_complex8_t *x,int *incx,blapi_complex8_t *y,int *incy); 
int FORTRAN (*ptr_icamax)(int *n,blapi_complex8_t *x,int *incx); 
double FORTRAN (*ptr_dasum)(int *n,double *x,int *incx);
void FORTRAN (*ptr_daxpy)(int *n,double *alpha,double *x,int *incx,double *y,int *incy);
void FORTRAN (*ptr_dcopy)(int *n,double *x,int *incx,double *y,int *incy);
double FORTRAN (*ptr_ddot)(int *n,double *x,int *incx,double *y,int *incy);
double FORTRAN (*ptr_dnrm2)(int *n,double *x,int *incx);
void FORTRAN (*ptr_drot)(int *n,double *x,int *incx,double *y,int *incy,double *c,double *s);
void FORTRAN (*ptr_drotg)(double *a,double *b,double *c,double *s);
void FORTRAN (*ptr_drotm)(int *n,double *x,int *incx,double *y,int *incy,double *param);
void FORTRAN (*ptr_drotmg)(double *d1,double *d2,double *x1,double *y1,double *param);
void FORTRAN (*ptr_dscal)(int *n,double *a,double *x,int *incx);
void FORTRAN (*ptr_dswap)(int *n,double *x,int *incx,double *y,int *incy);
double FORTRAN (*ptr_dzasum)(int *n,blapi_complex16_t *x,int *incx); 
double FORTRAN (*ptr_dznrm2)(int *n,blapi_complex16_t *x,int *incx); 
int FORTRAN (*ptr_idamax)(int *n,double *x,int *incx);
void FORTRAN (*ptr_zaxpy)(int *n,blapi_complex16_t *alpha,blapi_complex16_t *x,int *incx,blapi_complex16_t *y,int *incy); 
void FORTRAN (*ptr_zcopy)(int *n,blapi_complex16_t *x,int *incx,blapi_complex16_t *y,int *incy); 
void FORTRAN (*ptr_zdotc)(blapi_complex16_t *pres,int *n,blapi_complex16_t *x,int *incx,blapi_complex16_t *y,int *incy); 
void FORTRAN (*ptr_zdotu)(blapi_complex16_t *pres,int *n,blapi_complex16_t *x,int *incx,blapi_complex16_t *y,int *incy); 
void FORTRAN (*ptr_zdscal)(int *n,double *a,blapi_complex16_t *x,int *incx); 
void FORTRAN (*ptr_zrotg)(blapi_complex16_t *a,blapi_complex16_t *b,double *c,blapi_complex16_t *s); 
void FORTRAN (*ptr_zscal)(int *n,blapi_complex16_t *a,blapi_complex16_t *x,int *incx); 
void FORTRAN (*ptr_zswap)(int *n,blapi_complex16_t *x,int *incx,blapi_complex16_t *y,int *incy); 
int FORTRAN (*ptr_izamax)(int *n,blapi_complex16_t *x,int *incx); 
void FORTRAN (*ptr_sgbmv)(char *trans,int *m,int *n,int *kl,int *ku,float *alpha,float *a,int *lda,float *x,int *incx,float *beta,float *y,int *incy);
void FORTRAN (*ptr_sgemv)(char *trans,int *m,int *n,float *alpha,float *a,int *lda,float *x,int *incx,float *beta,float *y,int *incy);
void FORTRAN (*ptr_sger)(int *m,int *n,float *alpha,float *x,int *incx,float *y,int *incy,float *a,int *lda);
void FORTRAN (*ptr_ssbmv)(char *uplo,int *n,int *k,float *alpha,float *a,int *lda,float *x,int *incx,float *beta,float *y,int *incy);
void FORTRAN (*ptr_sspmv)(char *uplo,int *n,float *alpha,float *ap,float *x,int *incx,float *beta,float *y,int *incy);
void FORTRAN (*ptr_sspr)(char *uplo,int *n,float *alpha,float *x,int *incx,float *ap);
void FORTRAN (*ptr_sspr2)(char *uplo,int *n,float *alpha,float *x,int *incx,float *y,int *incy,float *ap);
void FORTRAN (*ptr_ssymv)(char *uplo,int *n,float *alpha,float *a,int *lda,float *x,int *incx,float *beta,float *y,int *incy);
void FORTRAN (*ptr_ssyr)(char *uplo,int *n,float *alpha,float *x,int *incx,float *a,int *lda);
void FORTRAN (*ptr_ssyr2)(char *uplo,int *n,float *alpha,float *x,int *incx,float *y,int *incy,float *a,int *lda);
void FORTRAN (*ptr_stbmv)(char *uplo,char *trans,char *diag,int *n,int *k,float *a,int *lda,float *x,int *incx);
void FORTRAN (*ptr_stbsv)(char *uplo,char *trans,char *diag,int *n,int *k,float *a,int *lda,float *x,int *incx);
void FORTRAN (*ptr_stpmv)(char *uplo,char *trans,char *diag,int *n,float *ap,float *x,int *incx);
void FORTRAN (*ptr_stpsv)(char *uplo,char *trans,char *diag,int *n,float *ap,float *x,int *incx);
void FORTRAN (*ptr_strmv)(char *uplo,char *transa,char *diag,int *n,float *a,int *lda,float *b,int *incx);
void FORTRAN (*ptr_strsv)(char *uplo,char *trans,char *diag,int *n,float *a,int *lda,float *x,int *incx);
void FORTRAN (*ptr_cgbmv)(char *trans,int *m,int *n,int *kl,int *ku,blapi_complex8_t *alpha,blapi_complex8_t *a,int *lda,blapi_complex8_t *x,int *incx,blapi_complex8_t *beta,blapi_complex8_t *y,int *incy); 
void FORTRAN (*ptr_cgemv)(char *trans,int *m,int *n,blapi_complex8_t *alpha,blapi_complex8_t *a,int *lda,blapi_complex8_t *x,int *incx,blapi_complex8_t *beta,blapi_complex8_t *y,int *incy); 
void FORTRAN (*ptr_cgerc)(int *m,int *n,blapi_complex8_t *alpha,blapi_complex8_t *x,int *incx,blapi_complex8_t *y,int *incy,blapi_complex8_t *a,int *lda); 
void FORTRAN (*ptr_cgeru)(int *m,int *n,blapi_complex8_t *alpha,blapi_complex8_t *x,int *incx,blapi_complex8_t *y,int *incy,blapi_complex8_t *a,int *lda); 
void FORTRAN (*ptr_chbmv)(char *uplo,int *n,int *k,blapi_complex8_t *alpha,blapi_complex8_t *a,int *lda,blapi_complex8_t *x,int *incx,blapi_complex8_t *beta,blapi_complex8_t *y,int *incy); 
void FORTRAN (*ptr_chemv)(char *uplo,int *n,blapi_complex8_t *alpha,blapi_complex8_t *a,int *lda,blapi_complex8_t *x,int *incx,blapi_complex8_t *beta,blapi_complex8_t *y,int *incy); 
void FORTRAN (*ptr_cher)(char *uplo,int *n,float *alpha,blapi_complex8_t *x,int *incx,blapi_complex8_t *a,int *lda); 
void FORTRAN (*ptr_cher2)(char *uplo,int *n,blapi_complex8_t *alpha,blapi_complex8_t *x,int *incx,blapi_complex8_t *y,int *incy,blapi_complex8_t *a,int *lda); 
void FORTRAN (*ptr_chpmv)(char *uplo,int *n,blapi_complex8_t *alpha,blapi_complex8_t *ap,blapi_complex8_t *x,int *incx,blapi_complex8_t *beta,blapi_complex8_t *y,int *incy); 
void FORTRAN (*ptr_chpr)(char *uplo,int *n,float *alpha,blapi_complex8_t *x,int *incx,blapi_complex8_t *ap); 
void FORTRAN (*ptr_chpr2)(char *uplo,int *n,blapi_complex8_t *alpha,blapi_complex8_t *x,int *incx,blapi_complex8_t *y,int *incy,blapi_complex8_t *ap); 
void FORTRAN (*ptr_ctbmv)(char *uplo,char *trans,char *diag,int *n,int *k,blapi_complex8_t *a,int *lda,blapi_complex8_t *x,int *incx); 
void FORTRAN (*ptr_ctbsv)(char *uplo,char *trans,char *diag,int *n,int *k,blapi_complex8_t *a,int *lda,blapi_complex8_t *x,int *incx); 
void FORTRAN (*ptr_ctpmv)(char *uplo,char *trans,char *diag,int *n,blapi_complex8_t *ap,blapi_complex8_t *x,int *incx); 
void FORTRAN (*ptr_ctpsv)(char *uplo,char *trans,char *diag,int *n,blapi_complex8_t *ap,blapi_complex8_t *x,int *incx); 
void FORTRAN (*ptr_ctrmv)(char *uplo,char *transa,char *diag,int *n,blapi_complex8_t *a,int *lda,blapi_complex8_t *b,int *incx); 
void FORTRAN (*ptr_ctrsv)(char *uplo,char *trans,char *diag,int *n,blapi_complex8_t *a,int *lda,blapi_complex8_t *x,int *incx); 
void FORTRAN (*ptr_dgbmv)(char *trans,int *m,int *n,int *kl,int *ku,double *alpha,double *a,int *lda,double *x,int *incx,double *beta,double *y,int *incy);
void FORTRAN (*ptr_dgemv)(char *trans,int *m,int *n,double *alpha,double *a,int *lda,double *x,int *incx,double *beta,double *y,int *incy);
void FORTRAN (*ptr_dger)(int *m,int *n,double *alpha,double *x,int *incx,double *y,int *incy,double *a,int *lda);
void FORTRAN (*ptr_dsbmv)(char *uplo,int *n,int *k,double *alpha,double *a,int *lda,double *x,int *incx,double *beta,double *y,int *incy);
void FORTRAN (*ptr_dspmv)(char *uplo,int *n,double *alpha,double *ap,double *x,int *incx,double *beta,double *y,int *incy);
void FORTRAN (*ptr_dspr)(char *uplo,int *n,double *alpha,double *x,int *incx,double *ap);
void FORTRAN (*ptr_dspr2)(char *uplo,int *n,double *alpha,double *x,int *incx,double *y,int *incy,double *ap);
void FORTRAN (*ptr_dsymv)(char *uplo,int *n,double *alpha,double *a,int *lda,double *x,int *incx,double *beta,double *y,int *incy);
void FORTRAN (*ptr_dsyr)(char *uplo,int *n,double *alpha,double *x,int *incx,double *a,int *lda);
void FORTRAN (*ptr_dsyr2)(char *uplo,int *n,double *alpha,double *x,int *incx,double *y,int *incy,double *a,int *lda);
void FORTRAN (*ptr_dtbmv)(char *uplo,char *trans,char *diag,int *n,int *k,double *a,int *lda,double *x,int *incx);
void FORTRAN (*ptr_dtbsv)(char *uplo,char *trans,char *diag,int *n,int *k,double *a,int *lda,double *x,int *incx);
void FORTRAN (*ptr_dtpmv)(char *uplo,char *trans,char *diag,int *n,double *ap,double *x,int *incx);
void FORTRAN (*ptr_dtpsv)(char *uplo,char *trans,char *diag,int *n,double *ap,double *x,int *incx);
void FORTRAN (*ptr_dtrmv)(char *uplo,char *transa,char *diag,int *n,double *a,int *lda,double *b,int *incx);
void FORTRAN (*ptr_dtrsv)(char *uplo,char *trans,char *diag,int *n,double *a,int *lda,double *x,int *incx);
void FORTRAN (*ptr_zgbmv)(char *trans,int *m,int *n,int *kl,int *ku,blapi_complex16_t *alpha,blapi_complex16_t *a,int *lda,blapi_complex16_t *x,int *incx,blapi_complex16_t *beta,blapi_complex16_t *y,int *incy); 
void FORTRAN (*ptr_zgemv)(char *trans,int *m,int *n,blapi_complex16_t *alpha,blapi_complex16_t *a,int *lda,blapi_complex16_t *x,int *incx,blapi_complex16_t *beta,blapi_complex16_t *y,int *incy); 
void FORTRAN (*ptr_zgerc)(int *m,int *n,blapi_complex16_t *alpha,blapi_complex16_t *x,int *incx,blapi_complex16_t *y,int *incy,blapi_complex16_t *a,int *lda); 
void FORTRAN (*ptr_zgeru)(int *m,int *n,blapi_complex16_t *alpha,blapi_complex16_t *x,int *incx,blapi_complex16_t *y,int *incy,blapi_complex16_t *a,int *lda); 
void FORTRAN (*ptr_zhbmv)(char *uplo,int *n,int *k,blapi_complex16_t *alpha,blapi_complex16_t *a,int *lda,blapi_complex16_t *x,int *incx,blapi_complex16_t *beta,blapi_complex16_t *y,int *incy); 
void FORTRAN (*ptr_zhemv)(char *uplo,int *n,blapi_complex16_t *alpha,blapi_complex16_t *a,int *lda,blapi_complex16_t *x,int *incx,blapi_complex16_t *beta,blapi_complex16_t *y,int *incy); 
void FORTRAN (*ptr_zher)(char *uplo,int *n,double *alpha,blapi_complex16_t *x,int *incx,blapi_complex16_t *a,int *lda); 
void FORTRAN (*ptr_zher2)(char *uplo,int *n,blapi_complex16_t *alpha,blapi_complex16_t *x,int *incx,blapi_complex16_t *y,int *incy,blapi_complex16_t *a,int *lda); 
void FORTRAN (*ptr_zhpmv)(char *uplo,int *n,blapi_complex16_t *alpha,blapi_complex16_t *ap,blapi_complex16_t *x,int *incx,blapi_complex16_t *beta,blapi_complex16_t *y,int *incy); 
void FORTRAN (*ptr_zhpr)(char *uplo,int *n,double *alpha,blapi_complex16_t *x,int *incx,blapi_complex16_t *ap); 
void FORTRAN (*ptr_zhpr2)(char *uplo,int *n,blapi_complex16_t *alpha,blapi_complex16_t *x,int *incx,blapi_complex16_t *y,int *incy,blapi_complex16_t *ap); 
void FORTRAN (*ptr_ztbmv)(char *uplo,char *trans,char *diag,int *n,int *k,blapi_complex16_t *a,int *lda,blapi_complex16_t *x,int *incx); 
void FORTRAN (*ptr_ztbsv)(char *uplo,char *trans,char *diag,int *n,int *k,blapi_complex16_t *a,int *lda,blapi_complex16_t *x,int *incx); 
void FORTRAN (*ptr_ztpmv)(char *uplo,char *trans,char *diag,int *n,blapi_complex16_t *ap,blapi_complex16_t *x,int *incx); 
void FORTRAN (*ptr_ztpsv)(char *uplo,char *trans,char *diag,int *n,blapi_complex16_t *ap,blapi_complex16_t *x,int *incx); 
void FORTRAN (*ptr_ztrmv)(char *uplo,char *transa,char *diag,int *n,blapi_complex16_t *a,int *lda,blapi_complex16_t *b,int *incx); 
void FORTRAN (*ptr_ztrsv)(char *uplo,char *trans,char *diag,int *n,blapi_complex16_t *a,int *lda,blapi_complex16_t *x,int *incx); 
void FORTRAN (*ptr_sgemm)(char *transa,char *transb,int *m,int *n,int *k,float *alpha,float *a,int *lda,float *b,int *ldb,float *beta,float *c,int *ldc);
void FORTRAN (*ptr_ssymm)(char *side,char *uplo,int *m,int *n,float *alpha,float *a,int *lda,float *b,int *ldb,float *beta,float *c,int *ldc);
void FORTRAN (*ptr_ssyr2k)(char *uplo,char *trans,int *n,int *k,float *alpha,float *a,int *lda,float *b,int *ldb,float *beta,float *c,int *ldc);
void FORTRAN (*ptr_ssyrk)(char *uplo,char *trans,int *n,int *k,float *alpha,float *a,int *lda,float *beta,float *c,int *ldc);
void FORTRAN (*ptr_strmm)(char *side,char *uplo,char *transa,char *diag,int *m,int *n,float *alpha,float *a,int *lda,float *b,int *ldb);
void FORTRAN (*ptr_strsm)(char *side,char *uplo,char *transa,char *diag,int *m,int *n,float *alpha,float *a,int *lda,float *b,int *ldb);
void FORTRAN (*ptr_cgemm)(char *transa,char *transb,int *m,int *n,int *k,blapi_complex8_t *alpha,blapi_complex8_t *a,int *lda,blapi_complex8_t *b,int *ldb,blapi_complex8_t *beta,blapi_complex8_t *c,int *ldc); 
void FORTRAN (*ptr_chemm)(char *side,char *uplo,int *m,int *n,blapi_complex8_t *alpha,blapi_complex8_t *a,int *lda,blapi_complex8_t *b,int *ldb,blapi_complex8_t *beta,blapi_complex8_t *c,int *ldc); 
void FORTRAN (*ptr_cher2k)(char *uplo,char *trans,int *n,int *k,blapi_complex8_t *alpha,blapi_complex8_t *a,int *lda,blapi_complex8_t *b,int *ldb,float *beta,blapi_complex8_t *c,int *ldc); 
void FORTRAN (*ptr_cherk)(char *uplo,char *trans,int *n,int *k,float *alpha,blapi_complex8_t *a,int *lda,float *beta,blapi_complex8_t *c,int *ldc); 
void FORTRAN (*ptr_csymm)(char *side,char *uplo,int *m,int *n,blapi_complex8_t *alpha,blapi_complex8_t *a,int *lda,blapi_complex8_t *b,int *ldb,blapi_complex8_t *beta,blapi_complex8_t *c,int *ldc); 
void FORTRAN (*ptr_csyr2k)(char *uplo,char *trans,int *n,int *k,blapi_complex8_t *alpha,blapi_complex8_t *a,int *lda,blapi_complex8_t *b,int *ldb,blapi_complex8_t *beta,blapi_complex8_t *c,int *ldc); 
void FORTRAN (*ptr_csyrk)(char *uplo,char *trans,int *n,int *k,blapi_complex8_t *alpha,blapi_complex8_t *a,int *lda,blapi_complex8_t *beta,blapi_complex8_t *c,int *ldc); 
void FORTRAN (*ptr_ctrmm)(char *side,char *uplo,char *transa,char *diag,int *m,int *n,blapi_complex8_t *alpha,blapi_complex8_t *a,int *lda,blapi_complex8_t *b,int *ldb); 
void FORTRAN (*ptr_ctrsm)(char *side,char *uplo,char *transa,char *diag,int *m,int *n,blapi_complex8_t *alpha,blapi_complex8_t *a,int *lda,blapi_complex8_t *b,int *ldb); 
void FORTRAN (*ptr_dgemm)(char *transa,char *transb,int *m,int *n,int *k,double *alpha,double *a,int *lda,double *b,int *ldb,double *beta,double *c,int *ldc);
void FORTRAN (*ptr_dsymm)(char *side,char *uplo,int *m,int *n,double *alpha,double *a,int *lda,double *b,int *ldb,double *beta,double *c,int *ldc);
void FORTRAN (*ptr_dsyr2k)(char *uplo,char *trans,int *n,int *k,double *alpha,double *a,int *lda,double *b,int *ldb,double *beta,double *c,int *ldc);
void FORTRAN (*ptr_dsyrk)(char *uplo,char *trans,int *n,int *k,double *alpha,double *a,int *lda,double *beta,double *c,int *ldc);
void FORTRAN (*ptr_dtrmm)(char *side,char *uplo,char *transa,char *diag,int *m,int *n,double *alpha,double *a,int *lda,double *b,int *ldb);
void FORTRAN (*ptr_dtrsm)(char *side,char *uplo,char *transa,char *diag,int *m,int *n,double *alpha,double *a,int *lda,double *b,int *ldb);
void FORTRAN (*ptr_zgemm)(char *transa,char *transb,int *m,int *n,int *k,blapi_complex16_t *alpha,blapi_complex16_t *a,int *lda,blapi_complex16_t *b,int *ldb,blapi_complex16_t *beta,blapi_complex16_t *c,int *ldc); 
void FORTRAN (*ptr_zhemm)(char *side,char *uplo,int *m,int *n,blapi_complex16_t *alpha,blapi_complex16_t *a,int *lda,blapi_complex16_t *b,int *ldb,blapi_complex16_t *beta,blapi_complex16_t *c,int *ldc); 
void FORTRAN (*ptr_zher2k)(char *uplo,char *trans,int *n,int *k,blapi_complex16_t *alpha,blapi_complex16_t *a,int *lda,blapi_complex16_t *b,int *ldb,double *beta,blapi_complex16_t *c,int *ldc); 
void FORTRAN (*ptr_zherk)(char *uplo,char *trans,int *n,int *k,double *alpha,blapi_complex16_t *a,int *lda,double *beta,blapi_complex16_t *c,int *ldc); 
void FORTRAN (*ptr_zsymm)(char *side,char *uplo,int *m,int *n,blapi_complex16_t *alpha,blapi_complex16_t *a,int *lda,blapi_complex16_t *b,int *ldb,blapi_complex16_t *beta,blapi_complex16_t *c,int *ldc); 
void FORTRAN (*ptr_zsyr2k)(char *uplo,char *trans,int *n,int *k,blapi_complex16_t *alpha,blapi_complex16_t *a,int *lda,blapi_complex16_t *b,int *ldb,blapi_complex16_t *beta,blapi_complex16_t *c,int *ldc); 
void FORTRAN (*ptr_zsyrk)(char *uplo,char *trans,int *n,int *k,blapi_complex16_t *alpha,blapi_complex16_t *a,int *lda,blapi_complex16_t *beta,blapi_complex16_t *c,int *ldc); 
void FORTRAN (*ptr_ztrmm)(char *side,char *uplo,char *transa,char *diag,int *m,int *n,blapi_complex16_t *alpha,blapi_complex16_t *a,int *lda,blapi_complex16_t *b,int *ldb); 
void FORTRAN (*ptr_ztrsm)(char *side,char *uplo,char *transa,char *diag,int *m,int *n,blapi_complex16_t *alpha,blapi_complex16_t *a,int *lda,blapi_complex16_t *b,int *ldb); 
