#//////////////////////////////////////////////////////////////////////////////
# blistbox & blistboxplus
#//////////////////////////////////////////////////////////////////////////////
mcset es "Delete all"        "Borrar todos"
mcset es "Select all"        "Seleccionar todos"
mcset es "Toggle selection"  "Invertir selección"
mcset es "Delete selected"   "Borrar seleccionados"
mcset es "Copy"              "Copiar"
mcset es "Copy all"          "Copiar todos"
mcset es "Copy selected"     "Copiar seleccionados"
mcset es "Count elements"    "Contar elementos"
mcset es "File_lbp"          "Archivo"
mcset es "Save to file"      "Guardar en un archivo"
mcset es "Load form file"    "Cargar desde un archivo"
mcset es "Unselect all"      "Deseleccionar todo"
mcset es "Copy unselect"     "Copiar deseleccionados"
mcset es "Selected"          "Selecionados"
mcset es "Not Selected"      "No Seleccionados"
mcset es "Filter"            "Filtrar"
mcset es "Unfilter"          "Quitar filtro"
mcset es "Insert element"    "Insertar elemento"


#//////////////////////////////////////////////////////////////////////////////
# bguifunction
#//////////////////////////////////////////////////////////////////////////////
mcset es "MustFillPar %1\$s"          "Debe rellenar el parametro %1\$s"

#//////////////////////////////////////////////////////////////////////////////
# bfilter
#//////////////////////////////////////////////////////////////////////////////
mcset es "Fields"                   "Campos"
mcset es "Operators"                "Operadores"
mcset es "Values"                   "Valores"
mcset es "Filters"                  "Filtros"
mcset es "Filtrate restrictions"    "Restricciones de filtrado"
mcset es "Add Options selected to Filter Frame" \
  "Añadir opción seleccionada al panel de Filtros"
mcset es "Apply Filter"             "Aplicar Filtro"
mcset es "To select an operator select a Field is needed" \
  "Para seleccionar un operador ha de seleccionar algún campo"
mcset es "You must type a language" "Debe pasarle un tipo de lenguaje al invocar el bfilter"
mcset es "You must select an operator" "Debe seleccionar un operador de la lista"
mcset es "You must select any Field" "Debe seleccionar algún campo de la lista"

mcset es "Filter Values A"           "Valores Filtro A"
mcset es "Filter Values B"           "Valores Filtro B"

mcset es "Equal to 'Filter Value A'"     "Igual al 'Valor del filtro A'"
mcset es "Not equal to 'Filter Value A'" "Distinto del 'Valor del filtro A'"
mcset es "Less than 'Filter Value A'"    "Menor que el 'Valor del filtro A'"
mcset es "Greater than 'Filter Value A'" "Mayor que el 'Valor del filtro A'"
mcset es "Greater than or equal to 'Filter Value A'" \
  "Mayor o igual que el 'Valor del filtro A'"
mcset es "Less than or equal to 'Filter Value A'" \
  "Menor o igual que el 'Valor del filtro A'"
mcset es "Greater than or equal to 'Filter Value A' and Less than or equal to 'Filter Value B'" \
  "Mayor o igual que el 'Valor del filtro A' y menor o igual que el 'Valor del filtro B'"
mcset es "Greater than 'Filter Value A' and Less than or equal to 'Filter Value B'" \
  "Mayor que el 'Valor del filtro A' y menor que el 'Valor del filtro B'"
mcset es "Greater than or equal to 'Filter Value A' and Less than 'Filter Value B'" \
  "Mayor o igual que el 'Valor del filtro A' y menor que el 'Valor del filtro B'"
mcset es "Greater than 'Filter Value A' and Less than 'Filter Value B'" \
  "Mayor que el 'Valor del filtro A' y menor que el 'Valor del filtro B'"
mcset es "Any element in set of 'Filter Value A'" \
  "Cualquier elemento perteneciente al conjunto de 'Valores del filtro A'"
mcset es "None element in set of 'Filter Value A'" \
  "Ningún elemento perteneciente al conjunto de 'Valores del filtro A'"
mcset es "Similar than 'Filter Value A'" "Parecido al 'Valor del filtro A'"


#//////////////////////////////////////////////////////////////////////////////
# beditmaster
#//////////////////////////////////////////////////////////////////////////////
mcset es "Key Fields"            "Campos Clave"
mcset es "Non Key Fields"        "Campos no Clave"
mcset es "Duplicate"             "Duplicar"
mcset es "New"                   "Nuevo"
mcset es "Edit"                  "Editar"
mcset es "Save"                  "Guardar"
mcset es "Save As"              "Guardar Como"
mcset es "Cancel"                "Cancelar"
mcset es "Delete"                "Borrar"
mcset es "Clear"                 "Limpiar"
mcset es "Refresh"               "Refrescar"
mcset es "Open"                  "Abrir"
mcset es "Exit"                  "Salir"
mcset es "askDeleteField"        "¿Confirma que desea borrar el registro activo?"
mcset es "Atention"              "Atención"
mcset es "notFillKey"            "Falta por rellenar los campos clave"
mcset es "notFillNotNull"        "Falta por rellenar los campos no nulos" 
mcset es "Save current"          "Grabar el registro actual"
mcset es "Cancel operation"      "Cancelar la operación"
mcset es "Edit current"          "Editar el registro actual"
mcset es "Delete current"        "Borrar el registro actual"
mcset es "Clear form"            "Borrar el formulario"
mcset es "Refresh form"          "Refrescar el formulario"
mcset es "Open table"            "Abrir tabla"
mcset es "Close window"          "Cerrar ventana"
mcset es "Edit Master"           "Editor Maestro"
mcset es "An error has taken place during the creation of the form, reason why this it could not be visualized" \
         "Se ha producido un error durante la creación del formulario, por lo que este no podrá ser visualizado"

#//////////////////////////////////////////////////////////////////////////////
# bentrydate
#//////////////////////////////////////////////////////////////////////////////
mcset es "Clear date"            "Borrar fecha"

#//////////////////////////////////////////////////////////////////////////////
# beditselector
#//////////////////////////////////////////////////////////////////////////////
mcset es "Attention"             "Atención"
mcset es "Value"	 	 "Valor"
mcset es "Insert"		 "Insertar"
mcset es "Add"		  	 "Añadir"
mcset es "Select from a List"	 "Seleccionar de una Lista"
mcset es "The option to select to all the elements of the list this disabled" \
           "La opción de seleccionar todos los elementos de la lista está deshabilitada"

#//////////////////////////////////////////////////////////////////////////////
# bodbc
#//////////////////////////////////////////////////////////////////////////////
mcset es "Connect options"  "Opciones de conexión"
mcset es "Connect"      "Conectar"
mcset es "Disconnect"   "Desconectar"
mcset es "Connection"   "Conexión"
mcset es "Alias"        "Alias"
mcset es "User"         "Usuario"
mcset es "Password"     "Contraseña"
mcset es ShowDialogODBC        \
        "Mostrar cuadro de conexión a la Base de Datos al arrancar TOLBase"
mcset es "Cancel"              "Cancelar"

#//////////////////////////////////////////////////////////////////////////////
# bfieldsdialog
#//////////////////////////////////////////////////////////////////////////////
mcset es "Apply"              "Aplicar"
mcset es "Add element"        "Añadir elemento"
mcset es "Accept"             "Aceptar"
mcset es "Accept element"     "Aceptar elemento"
mcset es "Exit dialog"        "Cerrar dialogo"
mcset es "Filter elements"    "Filtrar elementos"
mcset es "Filter Information" "Información del filtrado"

#//////////////////////////////////////////////////////////////////////////////
# bfunctions
#//////////////////////////////////////////////////////////////////////////////
mcset es "Abort" "Abortar"
mcset es "The path of the internet browser isn't established, using the default Windows browser" \
  "No se ha establecido la ruta del navegador, se utilizará el navegador por defecto de Windows"
mcset es "The path of the internet browser isn't established" \
  "No se ha establecido la ruta del navegador"
mcset es "The path of the PDF wiewer isn't established" \
  "No se ha establecido la ruta del visor de archivos PDF"
mcset es "The path of the help isn't correctly established" \
  "La ruta de la ayuda no se encuentra bien establecida"

#//////////////////////////////////////////////////////////////////////////////
# bcomboboxplus
#//////////////////////////////////////////////////////////////////////////////
mcset es "List of values"  "Lista de valores"
mcset es "Confirmation. Restart search" "Confirmación. Reiniciar búsqueda"
mcset es "You have arrived to the end of list. Do you want to restart search?" \
  "Ha llegado al final de la lista. ¿Quiere empezar desde el principio de nuevo?"
mcset es "No coincidence was found in list" "No se ha encontado coincidencia en la lista"
mcset es "Search in list"  "Buscar en la lista"

#//////////////////////////////////////////////////////////////////////////////
# bsersel
#//////////////////////////////////////////////////////////////////////////////
mcset es "Required fields"     "Campos obligatorios"
mcset es "Must fill subdimension %1\$s of dimension %2\$s" \
 "Debe rellenar la subdimensión %1\$s de la dimensión %2\$s"
mcset es "Series selected"     "Series seleccionadas"
mcset es "Add series to list"  "Añadir series a la lista"
mcset es "Clear selection"     "Limpiar selección"
mcset es "Clear all"           "Limpiar todos"
mcset es "Include"             "Incluir"
mcset es "Release"             "Liberar"
mcset es "Load selection from file"  "Cargar selección desde archivo"
mcset es "Save selection in file"    "Guardar selección en archivo"
mcset es "Close form"                "Cerrar el formulario"

mcset es "loading"                   "Cargando ..."
mcset es "Compiling serie"           "Compilando serie"
mcset es "Getting Values"            "Obteniendo valores para la selección de series"

#//////////////////////////////////////////////////////////////////////////////
# btable
#//////////////////////////////////////////////////////////////////////////////
mcset es "descdate%%" "Inserta un %"
mcset es "descdate%a" "Nombre del día de la semana abreviado (Lun, Mar, etc.)"
mcset es "descdate%A" "Nombre del día de la semana (Lunes, Martes, etc.)"
mcset es "descdate%b" "Nombre del mes abreviado (Ene, Feb, etc.)"
mcset es "descdate%B" "Nombre del mes completo"
mcset es "descdate%c" "El formato local de fecha y hora. EL formato local de fecha y hora en Unix/Mac es %a %b %d %H:%M:%S %Y. En Windows, este valor es el formato local largo de fecha y hora, tal como esta especificado en Configuración Regional del panel de control"
mcset es "descdate%C" "Primeros dos dígitos de los cuatro del año (19 o 20)"
mcset es "descdate%d" "Día del mes (01 - 31)"
mcset es "descdate%D" "Fecha como %m/%d/%y"
mcset es "descdate%e" "Día del mes (1 - 31), sin ceros"
mcset es "descdate%h" "Nombre del mes abreviado"
mcset es "descdate%H" "Hora en formato 24 horas (00 - 23)"
mcset es "descdate%I" "Hora en formato 12 horas (01 - 12)"
mcset es "descdate%j" "Día del año (001 - 366)"
mcset es "descdate%k" "Hora en formato 24 horas sin ceros (0 - 23)"
mcset es "descdate%l" "Hora en formato 12 horas sin ceros (1 - 12)"
mcset es "descdate%m" "Número del mes (01 - 12)"
mcset es "descdate%M" "Minuto (00 - 59)"
mcset es "descdate%n" "Salto de línea"
mcset es "descdate%p" "AM/PM"
mcset es "descdate%r" "Hora en formato específico meridiano. El formato meridiano en el locale C es %I:%M:%S %p"
mcset es "descdate%R" "Hora %H:%M"
mcset es "descdate%s" "Segundos desde el principio, expresados como un entero decimal"
mcset es "descdate%S" "Segundos (00 - 59)"
mcset es "descdate%t" "Tabulador"
mcset es "descdate%T" "Hora como %H:%M:%S"
mcset es "descdate%u" "Número del día de la semana (Lunes = 1, Domingo = 7)"
mcset es "descdate%U" "Semana del año (00 - 52), el domingo es el primer día de la semana"
mcset es "descdate%V" "Semana del año de acuerdo a la norma ISO-8601. La semana 1 de un año es aquella que contiene el 4 de Enero"
mcset es "descdate%w" "Número del día de la semana (Domingo = 0, Sábado = 6)"
mcset es "descdate%W" "Semana del año (00 - 52), el lunes es el primer día de la semana"
mcset es "descdate%x" "Formato de fecha local. El formato local para una fecha en Unix/Mac es %m/%d/%y. En Windows, este valor es el formato local de fecha corta, tal como esta especificado en Configuración Regional del panel de control"
mcset es "descdate%X" "El formato local de 24 horas. El formato local de 24 horas en Unix/Mac es %H:%M:%S. En Windows, este valor es el formato local de horas, tal como esta especificado en Configuración Regional del panel de control"
mcset es "descdate%y" "Dos últimos dígitos del año (00 - 99)"
mcset es "descdate%Y" "Año completo (1990)"
mcset es "descdate%Z" "Zona horaria"

mcset es "descreal%%" "Inserta un %."
mcset es "descreal%d" "Convierte un entero a una cadena decimal con signo"
mcset es "descreal%u" "Convierte un entero a una cadena decimal sin signo"
mcset es "descreal%i" "Convierte un entero a una cadena decimal con signo; el entero puede estar en formato decimal, octal (con un 0 delante) o hexadecimal (con 0x delante)"
mcset es "descreal%o" "Convierte un entero a una cadena octal sin signo"
mcset es "descreal%x" "Convierte un entero a una cadena hexadecimal sin signo, (usando ``0123456789abcdef'' para x y ``0123456789ABCDEF'' para X)"
mcset es "descreal%c" "Convert integer to the Unicode character it represents"
mcset es "descreal%s" "Sin conversion; solo inserta la cadena"
mcset es "descreal%f" "Convierte un número en coma flotante a un decimal con signo de la forma  xx.yyy, donde el número de ys esta determidado por la precisión (por defecto: 6). Si la precisión es 0 no se muestran dígitos decimales"
mcset es "descreal%e" "Convierte un número en coma flotante a notación científica de la forma x.yyye±zz, donde el número de ys esta determidado por la precisión (por defecto: 6). Si la precisión es 0 no se muestran dígitos decimales. Si se usa E, entonces se muestra E en lugar de e"
mcset es "descreal%g" "Si el exponente es menor que -4 o mayor o igual que la precisión, entonces se convierte el número de coma flotante como en %e or %E. En otro caso se convierte como en %f. Los ceros del final y la coma se omiten"

mcset es "Behaviour" "Comportamiento"
mcset es "Check whole table when changing types" "Comprueba toda la tabla al cambiar el tipo"
mcset es "Works with internal data" "Usar representación interna"
mcset es "Alternate row colors" "Alternar el color de las filas"
mcset es "Count" "Cuenta"
mcset es "Countn" "CuentaN"
mcset es "Count num" "CuentaN"
mcset es "None" "Ninguna"
mcset es "Avg" "Media"
mcset es "Set column type" "Tipo de columna"
mcset es "Set column format" "Tipo de formato"
mcset es "Mark all" "Marcar todas"
mcset es "Full word" "Palabra completa"
mcset es "name" "nombre"
mcset es "order" "orden"
mcset es "column" "columna"
mcset es "Side" "Dirección"
mcset es "Up" "Arriba"
mcset es "Abajo" "Abajo"
mcset es "Special copy" "Copiado especial"
mcset es "Copy headers" "Copiar cabeceras"
mcset es "Copy table" "Copiar tabla"
mcset es "Insert Rows" "Insertar Filas"
mcset es "Insert Columns" "Insertar Columnas"
mcset es "Order increasingly" "Orden ascendente"
mcset es "Order decreasingly" "Orden descendente"
mcset es "Advanced order" "Orden avanzado"
mcset es "Adjust table" "Ajustar tabla"

mcset es "CellNotReal" "El contenido de la celda no es un número real"
mcset es "CellNotDate" "El contenido de la celda no es una fecha"
mcset es "LikeChangeTypeText" "¿Quiere cambiar el tipo de la columna a texto?"
mcset es "TypeSetText" "El tipo sera cambiado a texto"
mcset es "SomeCellNotReal" "Algunas celdas no son números reales"
mcset es "SomeCellNotDate" "Algunas celdas no son fechas"
mcset es "Date format" "Formato de fecha"
mcset es "Real format" "Formato de real"
mcset es "Advanced selector of order" "Selector avanzado de orden"
mcset es "onlywin" "Esta función esta disponible solo en sistemas Windows"
mcset en "excellimit" "La tabla es demasiado grande para Excel"

#//////////////////////////////////////////////////////////////////////////////
# barima
#//////////////////////////////////////////////////////////////////////////////
mcset es "Add code"                       "Añadir código"
mcset es "Period"                         "Período"
mcset es "Difference"                     "Diferencias"
mcset es "Add code as key"                "Añadir código como clave"
mcset es "The parameters of MA are not valid" \
                         "Los parámetros de la parte MA no son válidos"
mcset es "The parameters of AR are not valid" \
                         "Los parámetros de la parte AR no son válidos"
mcset es "All the parameters of the model must be filled" \
                         "Deben rellenarse todos los parámetros del modelo"
mcset es "Clear parameters" \
                         "Limpiar los parámetros"
mcset es "Select the TimeSet"             "Seleccione el Fechado"
mcset es "TimeSet"                        "Fechado"
mcset es "Select or write the Period"     \
                         "Seleccione o escriba el Período"
mcset es "Select or write the Differences for this Period" \
               "Seleccione o escriba las Diferencias tomada para ese Período"
mcset es "Select or write the order of the AR for this Period" \
          "Seleccione o escriba el orden del polinomio AR para ese Período"
mcset es "Select or write the order of the MA for this Period" \
          "Seleccione o escriba el orden del polinomio AR para ese Período"
mcset es "Code of the ARIMA model" \
                        "Codigo del modelo ARIMA formado"
mcset es "Move to list"                   "Mover a la lista"
mcset es "Recove from list"               "Recuperar de la lista"
mcset es "Period required"                "Se requiere un Período"
mcset es "TimeSet required"               "Fechado requerido"
mcset es "Differences required"           \
              "Se requieren las Diferencias para ese Período"
mcset es "AR part required"               \
              "Se requiere la parte AR para ese Período"
mcset es "MA part required"               \
              "Se requiere la parte MA para ese Período"
mcset es "Period required"                "Se requiere un Período"
mcset es "Code of the ARIMA model required" \
              "Se requiere el código del modelo ARIMA"
#//////////////////////////////////////////////////////////////////////////////
# btab
#//////////////////////////////////////////////////////////////////////////////
mcset es "List" "Lista"
