#//////////////////////////////////////////////////////////////////////////////
# blistbox & blistboxplus
#//////////////////////////////////////////////////////////////////////////////
mcset po "Delete all"        "Apagar todos"
mcset po "Select all"        "Selecionar todos"
mcset po "Toggle selection"  "Inverter seleção"
mcset po "Delete selected"   "Apagar selecionados"
mcset po "Copy"              "Copiar"
mcset po "Copy all"          "Copiar todos"
mcset po "Copy selected"     "Copiar selecionados"
mcset po "Count elements"    "Contar elementos"
mcset po "File_lbp"          "Arquivo"
mcset po "Save to file"      "Salvar em um arquivo"
mcset po "Load form file"    "Carregar desde um arquivo"
mcset po "Unselect all"      "Deselecionar todo"
mcset po "Copy unselect"     "Copiar deselecionados"
mcset po "Selected"          "Selecionados"
mcset po "Not Selected"      "Não Selecionados"
mcset po "Filter"            "Filtrar"
mcset po "Unfilter"          "Eliminar filtro"
mcset po "Insert element"    "Inserir elemento"


#//////////////////////////////////////////////////////////////////////////////
# bguifunction
#//////////////////////////////////////////////////////////////////////////////
mcset po "MustFillPar %1\$s"          "Deve colocar o parâmetro %1\$s"

#//////////////////////////////////////////////////////////////////////////////
# bfilter
#//////////////////////////////////////////////////////////////////////////////

mcset po "Equal to"                 "Igual a"
mcset po "Not equal"                "Distinto"
mcset po "Less than"                "Menor que"
mcset po "Greater than"             "Maior que"
mcset po "Greater than or equal to" "Maior igual que"
mcset po "Less than or equal to"    "Menor igual que"
mcset po "Greater than or equal to % and Less than or equal to %" \
  "Mayor o igual que % y menor o igual que %"
mcset po "Greater than % and Less than or equal to %" \
  "Mayor que % y menor o igual que %"
mcset po "Greater than or equal to % and Less than %" \
  "Mayor o igual que % y menor que %"
mcset po "Greater than % and Less than %" "Mayor que % y menor que %"
mcset po "Any element in set: \[%\]" "Cualquier elemento comprendido en: \[%\]"
mcset po "None element in set: Not IN \[%\]" \
  "Ningun elemento comprendido en: \[%\]"

mcset po "Fields"                   "Campos"
mcset po "Operators"                "Operadores"
mcset po "Values"                   "Valores"
mcset po "Filters"                  "Filtros"
mcset po "Add Option"               "Añadir Opción de filtrado"
mcset po "Add Options selected to Filter Frame" \
  "Añadir opción seleccionada al panel de Filtros"
mcset po "Apply Filter"             "Aplicar Filtro"
mcset po "To select an operator select a Field is needed" \
  "Para seleccionar un operador ha de seleccionar algún campo"
mcset po "You must type a language" "Debe pasarle un tipo de lenguaje al invocar el bfilter"
mcset po "You must select an operator" "Debe seleccionar un operador de la lista"
mcset po "You must select any Field" "Debe seleccionar algún campo de la lista"


#//////////////////////////////////////////////////////////////////////////////
# beditmaster
#//////////////////////////////////////////////////////////////////////////////
mcset po "Key Fields"            "Campos Chave"
mcset po "Non Key Fields"        "Campos não Chave"
mcset po "Duplicate"             "Duplicar"
mcset po "New"                   "Novo"
mcset po "Edit"                  "Editar"
mcset po "Save"                  "Salvar"
mcset po "Cancel"                "Cancelar"
mcset po "Delete"                "Apagar"
mcset po "Clear"                 "Limpar"
mcset po "Refresh"               "Atualizar"
mcset po "Open"                  "Abrir"
mcset po "Exit"                  "Sair"
mcset po "askDeleteField"        "¿Confirma que deseja apagar o registro ativo?"
mcset po "Atention"              "Atenção"
mcset po "notFillKey"            "Falta colocar os campos chave"
mcset po "notFillNotNull"        "Falta colocar os campos não nulos" 
mcset po "Save current"          "Salvar o registro atual"
mcset po "Cancel operation"      "Cancelar a operação"
mcset po "Edit current"          "Editar o registro atual"
mcset po "Delete current"        "Apagar o registro atual"
mcset po "Clear form"            "Apagar o formulario"
mcset po "Refresh form"          "Refrescar el formulario"
mcset po "Open table"            "Abrir tabela"
mcset po "Close window"          "Fechar janela"
mcset po "Edit Master"           "Editor Maestro"
mcset po "An error has taken place during the creation of the form, reason why this it could not be visualized" \
         "Se ha producido un error durante la creación del formulario, por lo que este no podrá ser visualizado"

#//////////////////////////////////////////////////////////////////////////////
# bentrydate
#//////////////////////////////////////////////////////////////////////////////
mcset po "Clear date"            "Apagar data"

#//////////////////////////////////////////////////////////////////////////////
# beditselector
#//////////////////////////////////////////////////////////////////////////////
mcset po "Value"	 	       "Valor"
mcset po "Insert"		       "Inserir"
mcset po "Add"		  	 "Adicionar"
mcset po "Select from a List"	 "Selecionar de uma Lista"

#//////////////////////////////////////////////////////////////////////////////
# bodbc
#//////////////////////////////////////////////////////////////////////////////
mcset po "Connect options"  "Opções de coneção"
mcset po "Connect"      "Conetar"
mcset po "Disconnect"   "Desconetar"
mcset po "Connection"   "Coneção"
mcset po "Alias"        "Alias"
mcset po "User"         "Usuario"
mcset po "Password"     "Senha"
mcset po ShowDialogODBC        \
        "Mostrar cuadro de coneção na Base de Dados ao arrancar TOLBase"
mcset po "Cancel"              "Cancelar"

#//////////////////////////////////////////////////////////////////////////////
# bfieldsdialog
#//////////////////////////////////////////////////////////////////////////////
mcset po "Apply"              "Aplicar"
mcset po "Add element"        "Adicionar elemento"
mcset po "Accept"             "Aceitar"
mcset po "Accept element"     "Aceitar elemento"
mcset po "Exit dialog"        "Fechar dialogo"
mcset po "Filter elements"    "Filtrar elementos"
mcset po "Filter Information" "Informação do filtrado"

#//////////////////////////////////////////////////////////////////////////////
# bfunctions
#//////////////////////////////////////////////////////////////////////////////
mcset po "Abort" "Abortar"

#//////////////////////////////////////////////////////////////////////////////
# bcomboboxplus
#//////////////////////////////////////////////////////////////////////////////
mcset po "List of values"  "Lista de valores"

#//////////////////////////////////////////////////////////////////////////////
# bsersel
#//////////////////////////////////////////////////////////////////////////////
mcset po "Required fields"     "Campos obrigatórios"
mcset po "Must fill subdimension %1\$s in dimension %2\$s" \
 "Deve prencher a subdimensão %1\$s da dimensão %2\$s"
mcset po "Series selected"     "Series selecionadas"
mcset po "Add series to list"  "Adicionar series na lista"
mcset po "Clear selection"     "Limpar seleção"
mcset po "Clear all"           "Limpar todos"
mcset po "Include"             "Incluir"
mcset po "Release"             "Liberar"
mcset po "Load selection from file"  "Carregar seleção desde arquivo"
mcset po "Save selection in file"    "Guardar seleção em arquivo"
mcset po "Close form"                "Fechar o formulario"
mcset po "loading"                   "Carregando ..."
mcset po "Compiling serie"           "Compilando série"
mcset po "Getting Values"            "Obtendo valores para a seleção de séries"

#//////////////////////////////////////////////////////////////////////////////
# btable
#//////////////////////////////////////////////////////////////////////////////
mcset po "descdate%%" "Inserta um %"
mcset po "descdate%a" "Nome do día da semana abreviado (Seg, Ter, etc.)"
mcset po "descdate%A" "Nome do día da semana (Segunda, Terça, etc.)"
mcset po "descdate%b" "Nome do mês abreviado (Jan, Fev, etc.)"
mcset po "descdate%B" "Nome do mês completo"
mcset po "descdate%c" "Formato local de hora e data. O formato local de hora e data em Unix/Mac é %a %b %d %H:%M:%S %Y. Em Windows, este valor é o formato local longo de hora e data, tal como está especificado em Configuração Regional do Painel de Controle"
mcset po "descdate%C" "Primeiros dois dígitos dos cuatro do ano (19 o 20)"
mcset po "descdate%d" "Día do mês (01 - 31)"
mcset po "descdate%D" "Data como %m/%d/%y"
mcset po "descdate%e" "Día do mês (1 - 31), sem zeros"
mcset po "descdate%h" "Nome do mês abreviado"
mcset po "descdate%H" "Hora em formato 24 horas (00 - 23)"
mcset po "descdate%I" "Hora em formato 12 horas (01 - 12)"
mcset po "descdate%j" "Día do ano (001 - 366)"
mcset po "descdate%k" "Hora em formato 24 horas sem zeros (0 - 23)"
mcset po "descdate%l" "Hora em formato 12 horas sem zeros (1 - 12)"
mcset po "descdate%m" "Número do mês (01 - 12)"
mcset po "descdate%M" "Minuto (00 - 59)"
mcset po "descdate%n" "Salto de linha"
mcset po "descdate%p" "AM/PM"
mcset po "descdate%r" "Hora em formato específico meridiano. O formato meridiano no local é %I:%M:%S %p"
mcset po "descdate%R" "Hora %H:%M"
mcset po "descdate%s" "Segundos desde o princípio, expresados como um número decimal"
mcset po "descdate%S" "Segundos (00 - 59)"
mcset po "descdate%t" "Tabulador"
mcset po "descdate%T" "Hora como %H:%M:%S"
mcset po "descdate%u" "Número do día da semana (Segunda = 1, Domingo = 7)"
mcset po "descdate%U" "Semana do ano (00 - 52), domingo é o primeiro día da semana"
mcset po "descdate%V" "Semana do ano de acordo à norma ISO-8601. A semana 1 de um ano é aquela que contém o  4 de Janeiro"
mcset po "descdate%w" "Número do día da semana (Domingo = 0, Sábado = 6)"
mcset po "descdate%W" "Semana do ano (00 - 52), segunda é o primeiro día da semana"
mcset po "descdate%x" "Formato de data local. O formato local de hora e data em Unix/Mac é %a %b %d %H:%M:%S %Y. Em Windows, este valor é o formato local longo de hora e data, tal como está especificado em Configuração Regional do Painel de Controle"
mcset po "descdate%X" "Formato local de 24 horas. O formato local de hora e data em Unix/Mac é %a %b %d %H:%M:%S %Y. Em Windows, este valor é o formato local longo de hora e data, tal como está especificado em Configuração Regional do Painel de Controle"
mcset po "descdate%y" "Dois últimos dígitos do ano (00 - 99)"
mcset po "descdate%Y" "Ano completo (1990)"
mcset po "descdate%Z" "Zona horária"

mcset po "descreal%%" "Insere um %."
mcset po "descreal%d" "Converte um inteiro a uma cadeia decimal con signo"
mcset po "descreal%u" "Converte um inteiro a uma cadeia decimal sin signo"
mcset po "descreal%i" "Converte um inteiro a uma cadeia decimal con signo; el entero puede estar en formato decimal, octal (con un 0 delante) o hexadecimal (con 0x delante)"
mcset po "descreal%o" "Converte um inteiro a uma cadeia octal sin signo"
mcset po "descreal%x" "Converte um inteiro a uma cadeia hexadecimal sin signo, (usando ``0123456789abcdef'' para x y ``0123456789ABCDEF'' para X)"
mcset po "descreal%c" "Converte um inteiro ao carater Unicode que representa"
mcset po "descreal%s" "Sin conversion; solo inserta la cadena"
mcset po "descreal%f" "Convierte un número en coma flotante a un decimal con signo de la forma  xx.yyy, donde el número de ys esta determidado por la precisión (por defecto: 6). Si la precisión es 0 no se muestran dígitos decimales"
mcset po "descreal%e" "Convierte un número en coma flotante a notación científica de la forma x.yyye±zz, donde el número de ys esta determidado por la precisión (por defecto: 6). Si la precisión es 0 no se muestran dígitos decimales. Si se usa E, entonces se muestra E en lugar de e"
mcset po "descreal%g" "Si el exponente es menor que -4 o mayor o igual que la precisión, entonces se convierte el número de coma flotante como en %e or %E. En otro caso se convierte como en %f. Los ceros del final y la coma se omiten"

mcset po "Behaviour" "Comportamiento"
mcset po "Check whole table when changing types" "Comprueba toda la tabla al cambiar el tipo"
mcset po "Works with internal data" "Usar representación interna"
mcset po "Count" "Cuenta"
mcset po "Countn" "CuentaN"
mcset po "Count num" "CuentaN"
mcset po "None" "Ninguna"
mcset po "Avg" "Media"
mcset po "Set column type" "Tipo de columna"
mcset po "Set column format" "Tipo de formato"
mcset po "Mark all" "Marcar todas"
mcset po "Full word" "Palabra completa"
mcset po "name" "nombre"
mcset po "order" "orden"
mcset po "column" "columna"
mcset po "Side" "Dirección"
mcset po "Up" "Arriba"
mcset po "Abajo" "Abajo"
mcset po "Insert Rows" "Insertar Filas"
mcset po "Insert Columns" "Insertar Columnas"
mcset po "Order increasingly" "Orden ascendente"
mcset po "Order decreasingly" "Orden descendente"
mcset po "Advanced order" "Orden avanzado"
mcset po "Adjust table" "Ajustar tabla"

mcset po "CellNotReal" "El contenido de la celda no es un número real"
mcset po "CellNotDate" "El contenido de la celda no es una fecha"
mcset po "LikeChangeTypeText" "¿Quiere cambiar el tipo de la columna a texto?"
mcset po "TypeSetText" "El tipo sera cambiado a texto"
mcset po "SomeCellNotReal" "Algunas celdas no son números reales"
mcset po "SomeCellNotDate" "Algunas celdas no son fechas"
mcset po "Date format" "Formato de fecha"
mcset po "Real format" "Formato de real"

#//////////////////////////////////////////////////////////////////////////////
# barima
#//////////////////////////////////////////////////////////////////////////////
mcset po "Add code"                       "Adicionar código"
mcset po "Period"                         "Periodo"
mcset po "Difference"                     "Diferenças"
mcset po "Add code"                       "Adicionar código"
mcset po "The parameters of MA are not valid" \
                         "Os parâmetros da parte MA não são válidos"
mcset po "The parameters of AR are not valid" \
                         "Os parâmetros da parte AR não são válidos"
mcset po "All the parameters of the model must be filled" \
                         "Deveria colocar todos os parámetros do modelo"
mcset po "Clear parameters" \
                         "Limpar os parâmetros"
mcset po "Select the TimeSet"             "Seleccione el Fechado"
mcset po "TimeSet"                        "Fechado"
mcset po "Select or write the Period"     \
                         "Seleccione o escriba el Período"
mcset po "Select or write the Differences for this Period" \
               "Seleccione o escriba las Diferencias tomada para ese Período"
mcset po "Select or write the order of the AR for this Period" \
          "Seleccione o escriba el orden del polinomio AR para ese Período"
mcset po "Select or write the order of the MA for this Period" \
          "Seleccione o escriba el orden del polinomio AR para ese Período"
mcset po "Code of the ARIMA model" \
                        "Codigo del modelo ARIMA formado"
mcset po "Move to list"                   "Mover a la lista"
mcset po "Recove from list"               "Recuperar de la lista"
mcset po "Period required"                "Se requiere un Período"
mcset po "TimeSet required"               "Fechado requerido"
mcset po "Differences required"           \
              "Se requieren las Diferencias para ese Período"
mcset po "AR part required"               \
              "Se requiere la parte AR para ese Período"
mcset po "MA part required"               \
              "Se requiere la parte MA para ese Período"
mcset po "Period required"                "Se requiere un Período"
mcset po "Code of the ARIMA model required" \
              "Se requiere el código del modelo ARIMA"

