# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded bfunctions 1.0 [list source [file join $dir bflistbox.tcl]]\n[list source [file join $dir bflist.tcl]]\n[list source [file join $dir bfobjects.tcl]]\n[list source [file join $dir bfstring.tcl]]\n[list source [file join $dir bfunctions.tcl]]\n[list source [file join $dir autoscroll.tcl]]\n[list source [file join $dir bftoltcl.tcl]]\n[list source [file join $dir bfsql.tcl]]\n[list source [file join $dir progressbar.tcl]]\n[list source [file join $dir bltSend.tcl]]\n[list source [file join $dir bfmessages.tcl]]
