#-*-mode: TCL; coding: utf-8;-*-
#/////////////////////////////////////////////////////////////////////////////
# CATEGORIES OF THIS FILE
#  - Calendar Messages
#  - General Tolcon Messages
#  - Tolcon Options Messages
#  - Calendar Options Messages
#  - Object Inspector Messages
#  - Table Messages
#  - Table Options Messages
#  - Edit Table Messages
#  - Set Table Messages
#  - Graph Messages
#  - Graph Options Messages
#  - Selector Colums Graph
#  - Series Graph Messages
#  - Series Graph Options Messages
#  - Autocor Graph Options Messages
#  - Set Graph Messages
#  - Multiple Selector Messages
#  - Editor Messages
#  - Editor Options Messages
#  - Find Messages
#  - Statistics Series Messages
#  - Project Editor Messages
#  - Functions Search
#  - Draw Arima
#/////////////////////////////////////////////////////////////////////////////

#/////////////////////////////////////////////////////////////////////////////
# Calendar Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "January"     "Janeiro"
mcset po "February"    "Fevereiro"
mcset po "March"       "Março"
mcset po "April"       "Abril"
mcset po "May"         "Maio"
mcset po "June"        "Junho"
mcset po "July"        "Julho"
mcset po "August"      "Agosto"
mcset po "September"   "Setembro"
mcset po "October"     "Outubro"
mcset po "November"    "Novembro"
mcset po "December"    "Dezembro"
mcset po "Sun"  "Do"
mcset po "Mon"  "2f"
mcset po "Tue"  "3f"
mcset po "Wed"  "4f"
mcset po "Thu"  "5f"
mcset po "Fri"  "6f"
mcset po "Sat"  "Sa"

#/////////////////////////////////////////////////////////////////////////////
# General Tolcon Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "&File"      "&Arquivo"
mcset po "&New"       "&Novo"
mcset po "&Open"      "&Abrir"
mcset po "TOL &file"  "&Arquivo TOL"
mcset po "&Table"     "&Tabela"
mcset po "&Project"   "&Projeto"
mcset po "TOL &files" "&Arquivos TOL"
mcset po "&Tables"    "&Tabelas"
mcset po "&Projects"  "&Projetos"
mcset po "&Included"  "&Incluídos"
mcset po "Clear"      "Limpar"
mcset po "&Include"   "&Incluir"
mcset po "Include"    "Incluir"
mcset po "&Recent files"          "&Arquivos recentes"
mcset po "&Recent files (sorted)" "&Arquivos recentes (ordenado)"
mcset po "E&xit"                  "&Sair"
mcset po "Exit the application"   "Sair da aplicação"
mcset po "Question"               "Questões"
mcset po "Are you sure you want to quit?"  "Tem certeza que deseja sair?"
mcset po "&Tools"           "&Ferramentas"
mcset po "Tools"            "Ferramentas"
mcset po "TOL Editor"       "Editor do TOL"
mcset po "TOL &Editor"      "&Editor do TOL"
mcset po "&New TOL file"    "&Novo arquivo TOL"
mcset po "New TOL file"     "Novo arquivo TOL"
mcset po "&Open TOL file"   "&Abrir arquivo TOL"
mcset po "Open TOL file"    "Abrir arquivo TOL"
mcset po "TOL &Table Editor"    "Editor de &Tabelas de TOL"
mcset po "TOL Table Editor"     "Editor de Tabelas de TOL"
mcset po "&New Table"        "&Nova Tabela"
mcset po "New Table"         "Nova Tabela"
mcset po "&Open Table"       "&Abrir Tabela"
mcset po "Open Table"        "Abrir Tabela"
mcset po "TOL &Project Editor"     "Editor de &Projetos de TOL"
mcset po "TOL Project Editor"      "Editor de Projetos de TOL"
mcset po "&New Project"      "&Novo Projeto"
mcset po "New Project"       "Novo Projeto"
mcset po "&Open Project"     "&Abrir Projeto"
mcset po "Open Project"      "Abrir Projeto"
mcset po "Analysis Tools"      "Ferramentas de Análise"
mcset po "Draw ACF and PACF of ARIMA Models" \
         "Graficar ACF e PACF de Modelos ARIMA"
mcset po "&Functions Search"           "Búsqueda de &funções"
mcset po "Functions Search"            "Búsqueda de funções"
mcset po "&Calendar Expert"  "Experto em &Calendário"
mcset po "Calendar Expert"   "Experto em Calendário"
mcset po "C&onnection"       "C&onexão"
mcset po "Connection"       "Conexão"
mcset po "&Bayes SQL"        "&Bayes SQL"
mcset po "Bayes SQL"         "Bayes SQL"
mcset po "&Options"          "&Opções"
mcset po "Options"           "Opções"
mcset po "&Window"           "&Janela"
mcset po "Window"            "Janela"
mcset po "TOL Inspector"     "Inspetor de Objetos de TOL"
mcset po "TimeSets"          "TimeSets"
mcset po "Graphs"            "Gráficos"
mcset po "Files"             "Arquivos"
mcset po "Tables"            "Tabelas"
mcset po "Projects"          "Projetos"
mcset po "Close all"         "Fechar todas"
mcset po "&Help"             "&Ajuda"
mcset po "Help"              "Ajuda"
mcset po "&About"            "&Informação"
mcset po "About"             "Informação"
mcset po "TOL Objects"       "Objetos Tol"
mcset po "Grammars"          "Gramáticas"
mcset po "Included Files"    "Arquivos Incluídos"
mcset po "Console Objects"   "Objetos do Console"
mcset po "Objects' Spool"    "Spool de Objetos"
mcset po "Functions"         "Funções"
mcset po "Variables"         "Variaveis"
mcset po "Files"             "Arquivos"
mcset po "Output"          "Saída"
mcset po "Index"           "Índice"
mcset po "Name"            "Nome"
mcset po "Content"         "Conteúdo"
mcset po "Path"            "Caminho"
mcset po "Description"     "Descrição"
mcset po "Reference"       "Referência"
mcset po "OK"              "OK"
mcset po "Cancel"          "Cancelar"
mcset po "Apply"           "Aplicar"
mcset po "Close"           "Fechar"
mcset po "Options"         "Opções"
mcset po "Show Eval Window"    "Mostrar Janela Eval"
mcset po "Show Output Window"  "Mostrar Janela Output"
mcset po "Show Info Window"    "Mostrar Janela Info"
mcset po "Change View Mode"    "Mudar modo de visualización"
# Eval, Output and Info Windows
mcset po "Compile"         "Compilar"
mcset po "Decompile"       "Decompilar"
mcset po "Show history file"  "Mostrar arquivo de histórico"
mcset po "Syntax Check"       "Verificação de sintaxe"
mcset po "Delete all"         "Apagar tudo"
mcset po "Recover from log"   "Recuperar do log"
# Window Menu
mcset po "Tile across"	        "Telha"
mcset po "Tile Horizontally"    "Telha Horizontal"
mcset po "Tile Vertically"      "Telha Vertical"
mcset po "Cascade"              "Cascata"
mcset po "Arrange icons"        "Ordenar ícones"
mcset po "Minimize all"         "Minimizar todas"

#/////////////////////////////////////////////////////////////////////////////
# Tolcon Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "TOLBase Options"     "Opções de TOLBase"
mcset po "TOL"          "TOL"
mcset po "Default dates"       "Datas por padrão"
mcset po "First date"          "Data do começo"
mcset po "Last date"           "Data do Fim"
mcset po "Output"              "Saída"
mcset po "Write"               "Escrita"
mcset po "Write messages in output window"  \
  "Escrever mensagens na tela de saída"
mcset po "Errors color"     "Cor de erros"
mcset po "Warnings color"   "Cor dos avisos"
mcset po "Update"        "Atualização"
mcset po "Update options"   "Opções de atualização"
mcset po "Update always"    "Atualizar sempre"
mcset po "Update each"       "Atualizar um por um"
mcset po "milliseconds"       "mili-segundos"
mcset po "Don't update until the end"     "Não atualizar até o final"
mcset po "Precision"            "Precisão"
mcset po "Reduce decimal digits to"    "Reduzir o número de decimais para"
mcset po "digits"              "digitos"
mcset po "Use exponential notation when number has more than" \
 "Usar notação exponencial quando o número tenha mais que"
mcset po "Others"   "Outros"
mcset po "Files included recently"   "Arquivos incluídos recentemente"
mcset po "files"                     "arquivos"
mcset po "Language"                  "Linguagem"
mcset po "Choose language"          "Escolher linguagem"
mcset po "Language is set when you restart interface"  \
  "A linguagem será estabelecida quando reiniciar a interface"
mcset po "German"      "Alemão"
mcset po "English"     "Inglês"
mcset po "Spanish"     "Espanhol"
mcset po "French"      "Francês"
mcset po "Italian"     "Italiano"
mcset po "Japanese"    "Japonês"
mcset po "Dutch"       "Holandês"
mcset po "Portuguese"  "Português"
mcset po "Russian"     "Russo"
mcset po "Swedish"     "Sueco"
mcset po "Chinese"     "Chinês"
mcset po "Program paths"           "Rutas dos programas"
mcset po "Browser path"            "Ruta do navegador"
mcset po "PDF Viewer Path"         "Ruta do visor PDF"
mcset po "pathexplanation"         \
  "Debe especificar a ruta completa do programa ou só o nome do programa no \
 caso já esteja no path"
mcset po "Search the program path" "Procurar a ruta do programa"
mcset po ShowDialogODBC        \
  "Mostrar quadro de coneção da Base de Dados ao iniciar TOLBase"

#/////////////////////////////////////////////////////////////////////////////
# Calendar Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Calendar Options"    "Opções de calendário"
mcset po "General Options"     "Opções gerais"
mcset po "Appareance Options"  "Opções de Estilo"
mcset po "Highligth Appareance Options"    "Opções de Estilo para Ressaltar"
mcset po "Highligth"           "Ressaltado"
mcset po "Partial highligth"   "Ressaltado parcial"
mcset po "Full highligth"      "Ressaltado completo" 
mcset po "Type"      "Tipo"
mcset po "Fill"      "Recheio"
mcset po "Outline"   "Contorno"
mcset po "oval"         "ovalado"
mcset po "rectangle"      "retângulo"
mcset po "Month names"    "Nomes dos meses"
mcset po "Weekdays"       "Dias da semana"
mcset po "Month days"     "Dias do mês"
mcset po "Day"          "Dia"
mcset po "Month"        "Mês"
mcset po "Year"         "Ano"
mcset po "Rows"         "Linhas"
mcset po "Columns"      "Colunas"
mcset po "Language"     "Linguagem"
mcset po "TimeSet"      "TimeSet"
mcset po "Sunday starts week"    "Semana começa no domingo"
mcset po "Other days"         "Outros dias"
mcset po "Zoom In"           "Aumentar zoom"
mcset po "Zoom Out"          "Diminuir zoom"
mcset po "Moves to previous year"      "Ir ao ano antrior"
mcset po "Moves to previous month"     "Ir ao mês anterior"
mcset po "Moves to next month"         "Ir ao mês seguinte"
mcset po "Moves to next year"          "Ir ao ano seguinte"
mcset po "Moves to previous %1\$d months"     "Retroceder %1\$d meses"
mcset po "Moves to next %1\$d months"         "Avançar %1\$d meses"

#/////////////////////////////////////////////////////////////////////////////
# Object Inspector Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Table matrix"            "Tabelar matriz"
mcset po "Draw matrix"             "Graficar matriz"
mcset po "Draw serie"              "Graficar série"              
mcset po "Draw series"             "Graficar séries"
mcset po "Table serie"             "Tabelar série"
mcset po "Table series"            "Tabelar séries"
mcset po "Table statistics"        "Tabelar estatísticos"
mcset po "Draw autocorrelation"    "Graficar autocorrelação"
mcset po "Table autocorrelation"   "Tabelar autocorrelação"
mcset po "View timeset"            "Ver conjunto temporal"
mcset po "Export matrix"           "Exportar matriz"
mcset po "Draw set"                "Graficar conjunto"
mcset po "Table set"               "Tabelar conjunto"
mcset po "View file"               "Editar arquivo"
mcset po "Decompile file"          "Decompilar arquivo"
mcset po "View %1\$s's definition" "Ver definição de %1\$s"
mcset po "Add to spool"            "Adicionar ao spool" 
mcset po "Remove from spool"       "Retirar do spool"
mcset po "To Eval window"          "Á janela Eval"
mcset po "Select all"              "Seleccionar tudo"
mcset po "Toggle selection"        "Invertir seleção"
mcset po "Matrix table"            "Tabela de matriz"
mcset po "Time series graph"       "Gráfico de series"
mcset po "Autocorrelation graph"   "Gráfico de autocorrelação"
mcset po "Time series table"       "Tabela de séries"
mcset po "Autocorrelation table"   "Tabela de autocorrelação"
mcset po "Statistics table"        "Tabela de estatísticos"
mcset po "TimeSet calendar"        "Calendário de conjunto temporal"
mcset po "TimeSets calendar"       "Calendario dos conjuntos temporais"
mcset po "Dispersion graph"        "Gráfico de dispersão de um conjunto"
mcset po "Set table"               "Tabela de conjunto"
mcset po "Object %1\$s is a system TOL object" "O objeto %1\$s é um objeto TOL de sistema"
mcset po "Object %1\$s is not defined in a tol file" "O objeto %1\$s não está definido em um arquivo tol"
mcset po "Set not tabulable"       "Conjunto não tabelável"
mcset po "Set not graficable"      "Conjunto não graficável"
mcset po "Function %1\$s couldn't be stored in spool" \
  "A função  %1\$s não pudo ser adicionada ao spool"
mcset po VarWithoutNameNotFunc \
  "Não pode aplicar uma função sobre um objeto global sem nome"

#/////////////////////////////////////////////////////////////////////////////
# Functions search Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Search functions"            "Procurar funções"
mcset po "of grammars"                 "das gramáticas"
mcset po "whose name contains"         "cujo nome contem"
mcset po "whose description contains"  "cuja descrição contem"
mcset po "and with at least"           "e com ao menos"
mcset po "parameters"                  "parámetros"
mcset po "in which one is of type"     "dos quais um é de tipo"
mcset po "and whose name contains"     "e cujo nome contem"
mcset po "Has not been any coincident result" "Não se acharom resultados coincidentes"
mcset po "Message"                     "Mensaje"

#/////////////////////////////////////////////////////////////////////////////
# Table Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Export"    "Exportar"
mcset po "Free Headers"    "Cabeçalhos livres"
mcset po "Fixed Headers"   "Cabeçalhos fixos"
mcset po "Save"           "Salvar"
mcset po "Save as"        "Salvar como"
mcset po "Warning"        "Aviso"
mcset po "File hasn't been saved"  "O arquivo não foi salvo"
mcset po "Back"           "Anterior"
mcset po "Next"           "Seguinte"
mcset po "Filter"         "Filtrar"
mcset po "Row"            "Lin"
mcset po "Col"            "Col"
mcset po "rows"           "linhas"
mcset po "title"          "título"
mcset po "Eliminate"      "Eliminar"

#/////////////////////////////////////////////////////////////////////////////
# Table Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Table Options"      "Opções de Tabela"
mcset po "Export"           "Exportar"
mcset po "Style"            "Estilo"
mcset po "Columns separator"    "Separador de colunas"
mcset po "Rows separator"       "Separador de filas"
mcset po "Tab"           "Tabulador"
mcset po "Return"        "Salto de linha"
mcset po "Other"         "Outro"
mcset po "Number of rows to use as title area"   "Número de filas para o título"
mcset po "Number of columns to use as title area"  "Número de colunas para o título"
mcset po "Allow title cells in the selection"     "Permitir selecionar pilhas de título"

#/////////////////////////////////////////////////////////////////////////////
# Edit Table Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "New white table"              "Nova tabela em branco"
mcset po "Table %1\$s has changed!"    "¡A tabela do arquivo %1\$s mudou!"

#/////////////////////////////////////////////////////////////////////////////
# Set Table Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Set not tabulable"           "Conjunto não tabelable"

#/////////////////////////////////////////////////////////////////////////////
# Graph Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Zoom extend"
mcset po "Zoom frame"
mcset po "Scroll view"
mcset po "Toggle grid mode"            "Cambiar modo de grid"
mcset po "Toggle crosshair mode"       "Cambiar modo de puntero"
mcset po "Skip to first data"          "Saltar ao primer dado"
mcset po "Play backward"               "Reproducir hacia atrás"
mcset po "Stop playing"                "Parar reprodução"
mcset po "Play forward"                "Reproducir hacia delante"
mcset po "Skip to last data"           "Saltar ao último dado"
mcset po "Take a photo of the grafic"  "Guardar uma foto do gráfico"
mcset po "Copy to clipboard"           "Copiar na área de transferência"
mcset po "View as table"               "Visualizar como tabela"
mcset po "Changes type for all elements in graph" \
   "Cambia el tipo a todos los elementos del gráfico"
mcset po "Graphic Options"             "Opções do gráfico"
mcset po "Load graph options from a Graphic Configuration File" \
  "Carregar opções de gráfico desde um GCF (arquivo de configuração de gráficos)"
mcset po "Save the current graph options in a Graphic Configuration File" \
  "Salvar opções de gráfico num GCF (arquivo de configuração de gráficos)"

#/////////////////////////////////////////////////////////////////////////////
# Graph Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Graph Options"   "Opções de gráfico"
mcset po "General"         "Geral"
mcset po "Axis"            "Eixos"
mcset po "Titles"          "Títulos"
mcset po "Lines"           "Linhas"
mcset po "Data"            "Dados"
mcset po "Marker"          "Marcador"
mcset po "Markers"         "Marcadores"
mcset po "Grid"            "Grade"
mcset po "Legend"          "Legenda"
mcset po "Style"           "Estilo"
mcset po "Fill"            "Recheio"
mcset po "X Axis"          "Eixo X"
mcset po "Y Axis"          "Eixo Y"
mcset po "Ticks"           "Marcas"
mcset po "First"           "Primeiro"
mcset po "Last"            "último"
mcset po "Min"             "Mínimo"
mcset po "Max"             "Máximo"
mcset po "All values"      "Todos os valores"
mcset po "Total"           "Total"
mcset po "Each"            "Cada"
mcset po "Automatic"       "Automático"
mcset po "X2 Axis"         "Eixo X2"
mcset po "Y2 Axis"         "Eixo Y2"
mcset po "Show X2 axis"    "Mostrar eixo X2"
mcset po "Show Y2 axis"    "Mostrar eixo Y2"
mcset po "Data values"     "Valores dos dados"
mcset po "Data symbols"    "Símbolos dos dados"
mcset po "Show"         "Mostrar"
mcset po "both"         "ambos"
mcset po "none"         "nenhum"
mcset po "Show ticks"   "Mostrar marcas"
mcset po "Font"         "Fonte"
mcset po "Color"        "Cor"
mcset po "Shadow"       "Sombra"
mcset po "Rotate"       "Rodar"
mcset po "Length"       "Comprimento"
mcset po "Subdivisions" "Subdivisões"
mcset po "Graph Title"  "Título do gráfico"
mcset po "Axis Titles"  "Títulos dos eixos"
mcset po "X axis"       "eixo X"
mcset po "Y axis"       "eixo Y"
mcset po "X2 axis"      "eixo X2"
mcset po "Y2 axis"      "eixo Y2"

mcset po "Lines"        "Linhas"
mcset po "and"          "e"
mcset po "Bars"         "Barras"
mcset po "Bars Width"   "Largura de barras"
mcset po "Lines Width"  "Largura de linhas"
mcset po "Lines Type"   "Tipo de linhas"
mcset po "Smooth"       "Suavizado"
mcset po "linear"       "linear"
mcset po "step"         "degrau"
mcset po "natural"      "natural"
mcset po "quadratic"    "quadrático"
mcset po "Bar mode"     "Tipo de barras"
mcset po "aligned"      "alinhadas"
mcset po "stacked"      "apiladas"
mcset po "overlap"      "solapadas"
mcset po "infront"      "superpuestas"
mcset po "Bar relief"   "Relieve de barras"
mcset po "Elements order"  "Ordem dos elementos"
mcset po "Favourite line colors"   "Cores de linhas predeterminados"
mcset po "Color"      "Cor"
mcset po "Width"      "Largura"
mcset po "Decimals"   "Decimais"
mcset po "Anchor"     "Apoio"
mcset po "Show symbols"   "Mostrar símbolos"
mcset po "Symbol"    "Símbolo"
mcset po "circle"    "círculo"
mcset po "square"    "quadrado"
mcset po "diamond"   "diamante"
mcset po "plus"      "mais"
mcset po "cross"     "cruz"
mcset po "splus"     "peque mais"
mcset po "scross"    "peque cruz"
mcset po "triangle"  "triângulo"
mcset po "arrow"     "flecha"
mcset po "Pixels"    "Pixels"
mcset po "Scale symbols"   "Escala dos símbolos"
mcset po "Outline width"   "Largura do contorno"
mcset po "Grid options"       "Opções da grade"
mcset po "Line width"         "Largura da linha"
mcset po "Draw for minor ticks"    "Desenhar com marcas menores"
mcset po "Map X to"          "Aplicar X a"
mcset po "Map Y to"          "Aplicar Y a"
mcset po "Legend options"    "Opções de legenda"
mcset po "Hide legend"       "Ocultar legenda"
mcset po "Background"        "Cor de fundo"
mcset po "Border width"      "Largura da borda"
mcset po "Relief"            "Saliência"
mcset po "flat"              "plano"
mcset po "groove"            "ranurado"
mcset po "raised"            "levantado"
mcset po "ridge"             "sulco"
mcset po "solid"             "sólido"
mcset po "sunken"            "afundado"
mcset po "Position"          "posição"
mcset po "left"              "esquerda"
mcset po "right"             "direita"
mcset po "top"               "em cima"
mcset po "bottom"            "embaixo"
mcset po "plotarea"          "gráfico"
mcset po "Raised"            "levantado"
mcset po "X pad (left | right)"   "Espaço em X (esquerda | direita)"
mcset po "Y pad (top | bottom)"   "Espaço em Y (em cima | em baixo)"
mcset po "Internal"         "Interno"
mcset po "External"         "Externo"
mcset po "Graph"         "Gráfico"
mcset po "Exterior Area"    "Área exterior"
mcset po "MARGINS"    "MARGENS"
mcset po "Left"    "Esquerda"
mcset po "Right"   "Direita"
mcset po "Top"     "Em cima"
mcset po "Bottom"  "Em baixo"
mcset po "auto"    "auto"
mcset po "Plot Area"    "Área de Desenho"
mcset po "PAD"   "ESPAÇOS"
mcset po "Invert X-Y axis"  "Inverter eixos X-Y"
mcset po "Change color"     "Mudar a cor"
mcset po "Without color"    "Sem cor"
mcset po "Change font"      "Mudar a fonte"
mcset po "Change Shadow"    "Mudar a cor da sombra"
mcset po "Title"      "Título"
mcset po "Line"       "Linha"
mcset po "Common Options"      "Opções comuns"
mcset po "Line Options"        "Opções de linha"
mcset es "Bar Options"         "Opções de barra"
mcset po "Hide element"        "Ocultar elemento"
mcset po "Change type"         "Mudar tipo"
mcset po "Marker already inserted"       "Marcador já insertado"
mcset po "Fill options"  "Opções de recheio"
mcset po "Choose fill type, image or foreground and backgrounds colors for 5 Lines"\
  "Escolha tipo de recheio, imagen ou cor e cor de findo para as 5 primeras linhas"
mcset po "Fill type"  "Tipo de Preenchimento"
mcset po "Image"      "Imagem"
mcset po "image"      "imagem"
mcset po "striped"    "rayado"
mcset po {stipple image}    {Fundo com imagem}
mcset po {stipple degraded} {Fundo degradado}
mcset po {Image background} {Imagem de fundo}
mcset po {Degraded percentage} {Porcentagem degradado}
mcset po "Fill next lines after 5 with default style" \
  "Preencher as seguintes linhas começando pela 5ª com o estilo padrão"
mcset po "ForNumOpc:-" "Especifica que a conversão se justifica pela esquerda"
mcset po "ForNumOpc:+" "Especifica que o número se apresenta com sinal" 
mcset po "ForNumOpc:Space" \
  "Especifica que se adiciona um espaço em branco antes do número se o primeiro carater nõ é o sinal"
mcset po "ForNumOpc:Zero" \
  "Especifica que deve-se preencher o número com zeros à esquerda"
mcset po "ForNumOpc:f" \
  "Converte um número decimal com sinal em um carater da forma xx.yy,\n\
   em que o número 'y' determina a precisão (por padrão 6).\n\
   Se a precisão for zero, o ponto decimal não existirá na saída"
mcset po "ForNumOpc:e" \
  "Converte um número decimal com sinal, em um com notação científica da forma x.yyye±zz,\n\
   em que o número 'y' determina a precisão (por padrão 6).\n\
   Se a precisão for zero, o ponto decimal não existirá na saída.\n\
   Se E for usado, E será mostrado na saída ao invés de e"
mcset po "ForNumOpc:g" \
  "Se o exponente for menor que -4 ou maior ou igual que a precisão,\n\
   a conversão do número em ponto flutuante realiza-se com %e ou %E.\n\
   Em outro caso usará %f. Os zeros e o ponto decimal arrastados são omitidos"
mcset po "No conversion: just insert %" "Não realiza a conversão, insere %"
mcset po "It proves the specified format" "Testa o formato especificado"
mcset po "Prove" "Teste"
mcset po "AddMarkSel"              "Adiciona a marca à seleção"
mcset po "Scales"                  "Escalas"
mcset po "Date"                    "Data"
mcset po "Number"                  "Número"
mcset po "Text"                    "Texto"
mcset po "By defect"               "Por Padrão"
mcset po "Specified"               "Especificadas"
mcset po "Main title"              "Título do gráfico"
mcset po "Self fit of values"      "Auto-ajuste aos valores"
mcset po "Self fit of axes to the data of the graph to open" \
         "Autoajustar os eixos do gráfico aos valores ao abrir"
mcset po {For all element options} {Para todos os elementos}
mcset po {Lines list}              {Lista de linhas}
mcset po {Hide line}               {Ocultar línea}
mcset po {Foreground}              {Primeiro plano}

#/////////////////////////////////////////////////////////////////////////////
# Selector Colums Graph
#/////////////////////////////////////////////////////////////////////////////
mcset po "Select series"          "Selecionar series"
mcset po "Automatic generation"   "Geração automática"
mcset po SetGraphAllFirst         "Todas contra a primeira"
mcset po SetGraphAllFirstHint     "Gera todas as combinações possíveis\
 para graficar a primeira coluna com as outras"
mcset po SetGraphAllGeneric       "Todas contra a genérica"
mcset po SetGraphAllGenericHint   "Gera todas as combinações possíveis\
 para graficar a coluna genérica com as outras"
mcset po SetGraphEvenUneven       "Ímpares contra pares"
mcset po SetGraphEvenUnevenHint   "Gera as combinações possíveis de\
 ímpares contra pares.\n  1 contra 2, 3 contra 4, etc."

#/////////////////////////////////////////////////////////////////////////////
# Series Graph Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Show/Hide Average"       "Mostrar/Ocultar Media"     
mcset po "Show/Hide Std. Dev."     "Mostrar/Ocultar Dev. Std."
mcset po "View Statistics table"   "Ver tabela de estatísticos"

#/////////////////////////////////////////////////////////////////////////////
# Series Graph Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Date Format"            "Formato das datas"
mcset po "Axis"                   "Eixos"
mcset po "X-Markers"              "Marcadores em X"
mcset po "Y-Markers"              "Marcadores em Y"
mcset po "TOL Long Format"    "Formato longo de TOL"
mcset po "TOL Short Format"   "Formato curto de TOL"
mcset po "User Defined"       "Definido pelo usuário"
mcset po "Format String"      "Cadeia de formato"
mcset po "Format"    "Formato"
mcset po "String"    "Cadeia"
mcset po "Sample"    "Exemplo"
mcset po "Format Specifiers"    "Especificadores de formato"
mcset po "Long Weekday"            "Dia da semana (grande)"
mcset po "Long Month Name"         "Nome do mês (grande)"
mcset po "Short Weekday"           "Dia da semana (grande)"
mcset po "Short Month Name"        "Nome do mês (pequeno)"
mcset po "Day Number"              "Dia do mês"
mcset po "Month Number"            "Número do mês"
mcset po "Two Year Digit"          "Ano (2 dígitos)"
mcset po "Four Year Digit"         "Ano (4 dígitos)"
mcset po "Forze uncompleted dates"  "Datas incompletas"
mcset po "Forze completed dates"    "Datas completas"
mcset po "Percent symbol (%)"       "Símbolo de porcentagem (%)"
mcset po "X-Axis Ticks"               "Marcas para o eixo X"
mcset po "Select TimeSets for axis"  \
  "Selecione os conjuntos temporais para os eixos"
mcset po "Select TimeSets to mark"   \
  "Selecione os conjuntos temporais seguintes"
mcset po "X-Markers Style"     "Estilo dos marcadores do eixo X"
mcset po "Choose lines color, type and width for 5 X-Markers"\
  "Selecione o cor, estilo e grossor das linhas para os 5 \
 primeiros marcadores do eixo X"
mcset po "Select Statistics to mark" "Selecione os estatísticos seguintes"
mcset po "of"  "de"
mcset po "Cant draw '%1\$s' y marker because its value is ?" \
 "Não pode mostra-se o marcador no eixo Y '%1\$s' porque o valor dele é ?"
mcset po "showDesc"    "Mostrar a descrição como nome da serie"
mcset po "Rest"        "Resto" 

#/////////////////////////////////////////////////////////////////////////////
# Autocor Graph Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Autocorrelation"       "Autocorrelação"
mcset po "Parameters"            "Parametros"
mcset po "Numbers of lags"       "Número de lags"
mcset po "Sigma factor"          "Fator de sigma"
mcset po "Sigma value"           "Valor de sigma"

#/////////////////////////////////////////////////////////////////////////////
# Set Graph Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Set not graphicable"  "Conjunto não graficável"
mcset po "Columns Selector"     "Seletor de colunas"
mcset po "X Values"             "Valores em X"
mcset po "Y Values"             "Valores em Y"
mcset po "Series to draw"       "Series a desenhar"
mcset po "Add"                  "Añadir"
mcset po "Delete"               "Borrar"
mcset po "You must fill X Values"    "Deve preencher Valores em X"
mcset po "You must fill Y Values"    "Deve preencher Valores em Y"
mcset po "You must specify a name"   "Deve especificar um nome"
mcset po "Item not selectionable"    "Elemento não selecionável"
mcset po "UniqueXAxis"     "Se escolhe uma coluna de texto, datas ou genérica \
 para os valores em X de uma serie, deve escolher essa coluna como valores em \
 X de todas as series."
mcset po "You have added another serie with this name" \
 "Você já adicionou uma série com esse nome"
mcset po "You must select a serie"   "Deve selecionar uma série"
mcset po "Series do not exist that to draw" "Não existem séries a desenhar"

#/////////////////////////////////////////////////////////////////////////////
# Multiple Selector Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Multiple Selector"     "Seletor múltiplo"
mcset po "Not selected"          "Não selecionados"
mcset po "Selected"              "Selecionados"
mcset po "Moves selection from left to right" \
  "Passa a seleção da esquerda à direita"
mcset po "Moves selection from right to left" \
  "Passa a seleção da direita à esquerda"
mcset po "Moves all from left to right"     \
  "Passa todos da esquerda para a direita"
mcset po "Moves all from rigth to left"     \
  "Passa todos da direita para a esquerda"
mcset po "Accept selection"       "Aceitar a seleção"
mcset po "Cancel selection"       "Cancelar a seleçao"

#/////////////////////////////////////////////////////////////////////////////
# Editor Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Bayes Editor"       "Editor da Bayes"
mcset po "Saved"             "Salvo"
mcset po "Not Saved"         "Não salvo"
mcset po "New white document"                "Novo documento em branco"
mcset po "Open"        "Abrir"
mcset po "Save"        "Salvar"
mcset po "Save as"     "Salvar como"
mcset po "Print"       "Imprimir"
mcset po "Preview"     "Apresentação preliminar"
mcset po "Find"         "Localizar"
mcset po "Find next"    "Localizar seguinte"
mcset po "Replace"      "Substituir"
mcset po "Replace all"  "Substituir tudo"
mcset po "Replace with" "Substituir com"
mcset po "Edit"        "Edição"
mcset po "Cut"         "Recortar"
mcset po "Copy"        "Copiar"
mcset po "Paste"       "Colar"
mcset po "Select all"  "Selecionar tudo"
mcset po "Delete"      "Deletar"
mcset po "Undo"        "Desfazer"
mcset po "Redo"        "Repetir"
mcset po "Ident"       "Aumentar tabulação"
mcset po "Unident"     "Diminuir tabulação"
mcset po "Font"        "Fonte"
mcset po "Save and Compile"            "Salvar e compilar"
mcset po "Decompile"                   "Decompilar"
mcset po "Syntax Check"                "Verificar sintaxe"
mcset po "Refresh"                     "Refrescar"
mcset po "Help on line"                "Ajuda"
mcset po "Show line numbers"         "Mostrar o número de linhas"
mcset oi "Enable mark line numbers"  "Permitir marcar o número de linhas"
mcset po "Show right margin line"  \
  "Mostrar/Ocultar linha da margem direita"
mcset po "Not Compiled"                "Não compilado"
mcset po "Compiled"                    "Compilado"
mcset po "Compiling"                   "Compilando"
mcset po "Insert"                      "Inserir"
mcset po "Overwrite"                   "Sobrescrever"
mcset po "lines"                       "linhas"
mcset po "Header file %1\$s doesn't exist"  \
  "O arquivo do cabeçalho %1\$s não existe"
mcset po "Functions file header %1\$s doesn't exist"  \
  "O arquivo de cabecera de funções %1\$s não existe"
mcset po "Check editor's options"            "Verifique as opções do editor"
mcset po "Insert function schema"            "Inserir planilha de função"
mcset po "File %1\$s has changed!"         	\
  "O texto do arquivo %1\$s mudou!"
mcset po "Do you want to save changes?"     \
  "Deseja salvar as mudanças?"
mcset po "Syntax errors in file"            \
  "Arquivo com erros sintácticos"
mcset po "Look over output window"          \
  "Revise a janela de output"
mcset po "Syntax check done successfully"   \
  "Revisão sintática realizada corretamente"
mcset po "Syntax check cannot be done"      \
  "Não foi possivel realizar a revisão sintática"
mcset po "File allready opened!"            \
  "O arquivo já está aberto!"

#/////////////////////////////////////////////////////////////////////////////
# Editor Options Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Headers"     "Cabeceiras"
mcset po "Others"      "Outros"
mcset po "Files of headers"              "Arquivos dos cabeçalhos"
mcset po "Insert header in new files"    "Inserir cabeçalhos em arquivos novos"
mcset po "Files Header"                  "Cabeçalhos de arquivos"
mcset po "Functions Header"              "Cabeçalhos de funções"
mcset po "Files edited recently"         "Arquivos editados recentemente"
mcset po "files"                         "arquivos"
mcset po "Show line at"                  "Mostrar linha em"
mcset po "characters"                    "caracteres"
mcset po "Characters to ident"           "Caracteres a identar"

#/////////////////////////////////////////////////////////////////////////////
#Find Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Case sensitive"         "Coincidir maiúsculas e minúsculas"
mcset po "Direction"              "Direção"
mcset po "Forward"                "Para baixo"
mcset po "Backward"               "Para cima"
mcset po "SearchUpEndDoc"         "Chegou ao final do documento"
mcset po "SearchUpBeginDoc"       "Chegou ao começo do documento"
mcset po "FindFromBegin"          "Deseja continuar desde o começo do documento?"
mcset po "FindFromEnd"            "Deseja continuar desde o final do documento?"

#/////////////////////////////////////////////////////////////////////////////
#Statistics Series Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "Count"               "Largura"
mcset po "Maximun"             "Máximo"
mcset po "Minimun"             "Mínimo"
mcset po "Sum"                 "Soma"
mcset po "Average"             "Média"
mcset po "Std. Dev."           "Desv. Pad."
mcset po "Varianze"            "Variânça"
mcset po "Asimetry"            "Asimetria"
mcset po "Kurtosis"            "Kurtosis"
mcset po "Median"              "Mediana"

#/////////////////////////////////////////////////////////////////////////////
# Project Editor Messages
#/////////////////////////////////////////////////////////////////////////////
mcset po "New white project"   "Novo projeto em branco"
mcset po "Project"             "Projeto"
mcset po "Add node"            "Adicionar nó"
mcset po "Open node"           "Abrir nó"
mcset po "Delete node"         "Apagar nó"
mcset po "Attributes"          "Atributos"
mcset po "Compile node"        "Compilar nó"
mcset po "Decompile node"      "Decompilar nó"
mcset po "Compile to the end"  "Compilar até o final"
mcset po "Select node type"    "Selecionar tipo de nó"
mcset po "Node type"           "Tipo de nó"
mcset po "TOL file"            "Arquivo TOL"
mcset po "BDT file"            "Arquivo BDT"
mcset po "BST file"            "Arquivo BST"
mcset po "Folder"              "Pasta"
mcset po "Continue"            "Continuar"
mcset po "File name"           "Nome de arquivo"
mcset po "Exclude in TOLBase"  "Excluir em TOLBase"
mcset po "Exclude in tol.exe"  "Excluir em tol.exe"
mcset po "Are you sure you want to delete node %1\$s?" \
       "¿Está seguro que deseja apagar o nó %1\$s?"

#/////////////////////////////////////////////////////////////////////////////
#  - Functions Search
#/////////////////////////////////////////////////////////////////////////////
mcset po "There isn't grammars where search"   \
         "Deve introduzir alguma gramática para realizar a pesquisa"
mcset po "There aren't sufficient criteria search"   \
      "Não foram introduzidos suficientes critérios de busca"
mcset po "Criteria search for the name are incorrect"   \
         "Os critérios de busca introduzidos para o nome são incorretos"
mcset po "Criteria search for the description are incorrect"   \
         "Os critérios de busca introduzidos para a descrição são incorretos"

#/////////////////////////////////////////////////////////////////////////////
#  - Draw Arima
#/////////////////////////////////////////////////////////////////////////////
mcset po "Date first"          "Data inicial"
mcset po "Date last"           "Data final"
mcset po "Draw"                "Graficar"
mcset po "All the required parameters must be filled" \
                "Todos os parámetros requeridos devem ser preenchidos"
mcset po "The date last must be higher than the date first" \
                "A data final deve ser posterior à inicial"
mcset po "Dates do not have the correct format" \
                "As datas não estão em formato correto"
mcset po "Date Selector"       "Seletor de Datas"
mcset po "Graph of ACFs and PACFs of ARIMA Model" \
                "Gráfico de ACFs y PACFs do Modelo ARIMA"
mcset po "Parameters of the graph" \
                "Parámetros do gráfico"
mcset po "Date first required" "Data inicial requerida"
mcset po "Date last required"  "Datafinal requerida"
mcset po "Draw ACF and PACF of ARIMA Model" \
                "Graficar ACF y PACF do modelo ARIMA" 